/*
 * PSYCHOLOGY concept library for the Geon GameHub questioner rebuild.
 * `previous` = foundational concepts, `next` = advanced concepts (NEW questioner).
 * Fields per concept:
 *   term / def       — NORMAL facet (definition recall, sibling defs as distractors)
 *   cue              — HARD facet (scenario → which concept)
 *   misconceptions   — INSANE facet (3 plausible-but-false statements about the term)
 *   setup/right/wrongs — IMPOSSIBLE facet (constraint scenario + correct plan + 3 flawed plans)
 */
"use strict";

const c = (term, def, cue, misconceptions, setup, right, wrongs) =>
  ({ term, def, cue, misconceptions, setup, right, wrongs });

const foundational = {
  "MIND MANIPULATIONS": [
    c("gaslighting", "making someone doubt their own memory or perception of real events",
      "Dana keeps insisting a meeting never happened, even after Aya rereads her own detailed notes, until Aya starts doubting the notes themselves.",
      ["telling a kind white lie to spare a friend's feelings", "raising your voice in the middle of a fair argument", "changing your opinion after hearing stronger evidence"],
      "A roommate keeps denying an agreement that Aya recorded. Aya wants to protect both the truth and the living situation without escalating.",
      "keep the recording, state the agreed terms calmly once, and put future agreements in writing",
      ["argue the point every night until the roommate finally admits it", "apologize for having a bad memory to restore the peace", "hide the recording and agree with the denial to avoid conflict"]),
    c("foot-in-the-door", "gaining a large agreement by first getting a small voluntary yes",
      "Mia asks a neighbor to sign a petition today; next week the same neighbor happily helps run her whole booth.",
      ["demanding a huge favor first so a smaller one feels easy", "offering payment before any request is even made", "refusing every small request so you always look firm"],
      "Leo wants a busy manager to host a full workshop but has no authority to require it, and the manager distrusts big sudden asks.",
      "ask the manager to answer five quick questions, then invite a short talk, then propose the workshop",
      ["open with the full workshop request and repeat it louder when refused", "book the venue first, then demand the manager fill it", "lure the manager in with a fake topic and reveal the workshop late"]),
    c("door-in-the-face", "following an unreasonably large request with a much smaller, real one",
      "Ken asks to borrow a car for the weekend, gets refused, then asks only for a ride to the station, which feels easy by comparison.",
      ["starting with a tiny request and growing it every day", "rejecting every request until the other person begs you to stop", "making your real request first and hiding the extras for later"],
      "A fundraiser needs fifty-dollar monthly donors, but most people shut the door at that figure, and she must stay fully honest.",
      "first mention the five-hundred-patron level, then invite the smaller fifty-dollar monthly pledge",
      ["hint the large gift is tax-dodged to pressure a refusal", "ask two hundred strangers for the big amount with no smaller option", "collect the small pledge, then secretly upgrade it later"]),
    c("scarcity pressure", "rushing a decision by claiming an offer or supply is about to disappear",
      "A seller announces that only one discounted unit remains and the price dies tonight, so Rey buys in a panic without comparing.",
      ["giving buyers extra time so they can compare calmly", "lowering the price because a buyer hesitated honestly", "explaining every product flaw before the purchase"],
      "An online shop honestly overstocked four hundred units. The manager wants steady sales without ever trapping customers.",
      "publish the real stock count and a real deadline, and hold the price steady after it passes",
      ["run a countdown timer that secretly resets every night", "claim two units remain while four hundred sit in storage", "quietly raise the price for visitors who return without buying"]),
    c("social proof", "pointing to what many others already do to make a choice feel safe",
      "An ad notes that nine of ten local shops already switched suppliers, and Bea suddenly feels she is the one falling behind.",
      ["paying strangers to post angry reviews about rivals", "hiding every customer number from the website", "removing all testimonials so buyers judge entirely alone"],
      "A clinic wants more families to book checkups and holds genuine high-turnout records it may share.",
      "show the real percentage of local families who booked this year, with the survey source and date",
      ["invent a survey that was never actually conducted", "quote only the two worst reviews of a competing clinic", "create fake five-star accounts with stock-photo faces"]),
    c("reciprocity pressure", "using an unasked-for gift to create a feeling of debt",
      "A vendor hands Rico a free snack at the door, then immediately suggests a huge order would be the fair way to say thanks.",
      ["thanking someone warmly without giving anything back", "splitting a shared meal bill exactly evenly", "politely refusing every gift so no relationship ever forms"],
      "A consultant wants more client referrals but refuses to pressure anyone.",
      "give help freely, mention referrals once as an option, and accept any no gracefully",
      ["mail gifts right before asking each client for ten referrals", "remind clients weekly that they owe for past favors", "hold a finished report back until referrals arrive"]),
    c("anchoring", "setting a first number that drags later estimates toward it",
      "A seller opens at 9,000, so the buyer's 6,500 counteroffer feels tiny even though 6,500 was already the buyer's ceiling.",
      ["researching market prices before naming any figure", "insisting the second number spoken is always the fair one", "rounding every price to the nearest thousand to be polite"],
      "A freelancer must price a project and wants a fair rate without steering the client.",
      "research standard rates, quote one honest figure, and justify it with a clear deliverables list",
      ["open at triple the real rate and call the padding room to negotiate", "cite an inflated rival quote the client cannot verify", "drop the huge anchor only when the client looks upset"]),
    c("framing", "steering a decision by how identical facts are worded, as gain or loss",
      "Two posters describe one glass the same way factually: 90 percent leak-proof versus fails once in ten — reactions split sharply.",
      ["changing the actual numbers to make results look better", "falsifying test data to flatter the product", "removing the choice entirely so no wording matters"],
      "A health officer must present one true vaccination statistic so worried parents decide carefully rather than blindly.",
      "show the success rate and the risk side by side, using the same clear numbers for both",
      ["lead with only the scariest outlier case to force compliance", "display only the success rate and refuse all questions", "reword the risk until it vanishes from the page"]),
    c("guilt-tripping", "controlling someone by blaming them for the controller's own feelings",
      "A teammate sighs that she will just do the whole report alone tonight, and Pia volunteers mostly to end the guilt.",
      ["saying directly that you felt hurt when plans changed", "apologizing once for a mistake you truly made", "asking plainly for help with your own task"],
      "A relative uses guilt to extract free babysitting every day; the parent needs a fair, workable arrangement.",
      "acknowledge the feeling, restate real availability, and offer fixed days instead of open-ended duty",
      ["give in daily and quietly collect resentment", "cut all contact after the very first sigh", "fire the same guilt back to win the argument"]),
    c("love bombing", "flooding a person with praise and gifts early to build dependency",
      "After one week a new partner sends fifty messages a day, promises a shared future home, and turns cold at any slow reply.",
      ["being steadily kind across years of stable friendship", "giving a sincere compliment when a friend truly earns one", "planning a wedding after two years of open, calm dating"],
      "Tess's new partner escalates gifts and demands constant replies; Tess wants to stay safe without becoming paranoid.",
      "slow the pace, keep her own routines and friends, and watch how the partner handles being told no",
      ["reply instantly to every message to keep the peace", "match every gift so the exchange feels balanced", "hide the relationship from friends so nobody interferes"])
  ],
  "SELF RESILIENCE": [
    c("growth mindset", "treating ability as something practice and feedback can grow",
      "After failing a driving test, Sam books extra practice and studies the examiner's notes instead of quitting.",
      ["believing talent alone decides every outcome", "refusing feedback to protect your confidence", "practicing only what you already do well"],
      "A tutor wants a failing student to keep trying after low mock scores, without empty praise.",
      "pair each mock result with one specific skill to drill next, and review the progress weekly",
      ["call the mocks unfair and skip the retakes", "praise effort alone and never adjust study methods", "compare the student daily with the top scorer"]),
    c("self-efficacy", "confidence that you can carry out the specific task in front of you",
      "Rhea has swum countless laps, so at the race she calmly trusts her own strokes instead of watching rivals.",
      ["assuming confidence in one area transfers everywhere with no practice", "believing luck alone decides who finishes", "avoiding all challenges to protect your self-image"],
      "A new nurse freezes at the thought of code responses; the educator must build true readiness, not slogans.",
      "run graded code simulations with feedback until the nurse leads one confidently",
      ["recite motivational lines and skip the drills", "keep the nurse observing codes for a full year", "assign the hardest case first to sink or swim"]),
    c("cognitive reappraisal", "reframing a stressful event's meaning without denying the facts",
      "Nico reads a harsh review as a map of what to fix next, not as proof that he is a failure.",
      ["pretending a real problem simply does not exist", "blaming other people for every setback", "numbing stress by avoiding all news and people"],
      "A dispatcher's shift went badly; the supervisor wants honest learning without shame spirals.",
      "review the timeline together, separate system faults from choices, and set two concrete fixes",
      ["call the shift totally fine and move on", "write up the dispatcher with no discussion", "ban all talk of the incident to protect morale"]),
    c("problem-focused coping", "reducing stress by directly changing the situation causing it",
      "Overwhelmed by a leaking roof, Ida calls three roofers and books the soonest repair instead of just venting.",
      ["using breathing exercises only while the crisis keeps growing", "endlessly listing worries without acting on any", "quitting every task that ever feels heavy"],
      "A student's stress comes from a real backlog of work; the coach must target the backlog itself.",
      "break the backlog into dated chunks, clear the oldest debt first, and track visible progress",
      ["prescribe relaxation apps while deadlines keep piling", "drop the course to erase the stressor entirely", "add more subjects to build tolerance"]),
    c("implementation intention", "linking a goal to a specific if-then plan of time and place",
      "Marta writes: if it is 7 a.m. on Monday, I study at the kitchen table — and the habit finally sticks.",
      ["writing vague wishes like study more soon", "setting goals and never choosing when or where", "depending on willpower alone each day"],
      "A rehab patient must do daily exercises but forgets most evenings.",
      "attach each exercise to an existing cue — after brushing teeth, before dinner — with the mat laid out",
      ["remind the patient to try harder to remember", "schedule all exercises sometime this weekend", "double the routine so missing it feels worse"]),
    c("recovery routine", "planned sleep, breaks, and support that restore capacity after strain",
      "After a brutal week, Jun schedules two real off-days, long sleeps, and a mentor check-in before the next push.",
      ["working every weekend to bounce back faster", "treating rest as a reward you must earn by burning out", "replacing sleep with extra caffeine"],
      "A startup team ships late nights for a month; the lead must prevent burnout without losing momentum.",
      "cap the crunch, schedule rotating rest days, and hold a short retro before the next sprint",
      ["promise a break after the next launch forever", "hand out energy drinks and extend the hours", "book another launch the morning after shipping"]),
    c("support network", "people you can honestly lean on for help, feedback, and backup",
      "When her plans collapse, Ana calls two trusted friends: one simply listens, one helps rewrite the plan.",
      ["collecting hundreds of contacts you never actually talk to", "depending on a single person for every need", "hiding all struggles so no one can ever help"],
      "A remote worker feels isolated; the manager must build real support without forced fun.",
      "set optional peer pairs, normalize brief help requests, and check workload in one-on-ones",
      ["mandate daily group video hangouts after hours", "tell the worker to toughen up remotely", "route all support through HR tickets only"]),
    c("self-compassion", "treating your own mistakes with the fairness you would give a friend",
      "After a missed deadline, Kim says this was a bad week, not a bad person — fixes the handoff, and moves on.",
      ["excusing every mistake so nothing ever improves", "calling yourself useless to stay motivated", "praising everyone else and never yourself"],
      "A perfectionist designer spirals after client rejections; the lead must keep both quality and morale.",
      "review each rejection for one actionable lesson, then close the file with a fixed next step",
      ["forward every harsh comment to the designer for honesty", "tell the designer the standards no longer matter", "remove all client feedback to shield the designer"]),
    c("boundary setting", "stating clearly what you will and will not accept, then holding it",
      "Noah tells his team he is offline after 7 p.m. and answers non-urgent pings the next morning.",
      ["saying yes to everything to avoid conflict", "exploding angrily when someone crosses an unstated line", "threatening to quit over every small request"],
      "A caregiver receives late-night calls that are never urgent; the clinic must protect both sides.",
      "define a true emergency list and an on-call rota, and route everything else to morning hours",
      ["silence the phone entirely with no escalation path", "ask the caregiver to just endure the calls", "give the caregiver's number to more departments"]),
    c("emotional regulation", "noticing feelings early and steering your response instead of being steered",
      "Feeling anger rise in a meeting, Tito pauses, breathes once, and asks for the data before replying.",
      ["suppressing every feeling until it bursts out", "expressing every impulse the moment it appears", "avoiding every situation that stirs any emotion"],
      "A call-center agent must stay effective through hostile calls without faking cheer.",
      "train brief reset pauses, use neutral scripts, and debrief hard calls with a peer after shift",
      ["scold the agent for feeling anything at all", "allow instant hang-ups on any rude caller", "move the agent to email work permanently"])
  ],
  "CONVINCE OTHERS": [
    c("active listening", "reflecting a person's real point back before you answer it",
      "So the deadline is the issue, not the budget? — the client nods, and the meeting finally moves forward.",
      ["waiting silently for your turn to talk", "interrupting with your own better story", "nodding along while typing replies to others"],
      "A support agent must de-escalate a furious customer and actually solve the case.",
      "mirror the complaint in one sentence, confirm it, then fix the named issue first",
      ["read a fixed script over the customer's words", "offer refunds before naming the real problem", "transfer the call twice to reset the meter"]),
    c("credible evidence", "supporting a claim with sources your audience can check",
      "Instead of saying studies show, Bea cites the 2023 city report with a link and a page number.",
      ["naming experts without any source at all", "citing a deleted blog only you can open", "treating one anonymous comment as proof"],
      "A barangay proposal for new streetlights faces a skeptical council.",
      "attach the accident map, vendor quotes, and two comparable town results with contacts",
      ["speak louder about common-sense safety", "print a petition with half-legible names", "promise the numbers next meeting, forever"]),
    c("common ground", "starting from what both sides already accept, then building outward",
      "We both want fewer complaints — from there the two managers compare tools instead of trading blame.",
      ["pretending to agree with everything they say", "opening with the most divisive point first", "ignoring the shared goal to win the round"],
      "Two departments fight over a shared calendar tool; the facilitator must align them fast.",
      "list both teams' agreed pains, test one tool for two weeks, and set shared success metrics",
      ["impose the director's favorite tool by decree", "run parallel tools forever to keep the peace", "merge the teams to erase the dispute"]),
    c("audience analysis", "shaping your message to what your listeners value and already know",
      "To farmers Marco compares loan terms in harvest bags, not spreadsheets; to bankers he flips the framing.",
      ["using identical jargon slides for every crowd", "assuming everyone shares your priorities", "speaking only to the loudest listener"],
      "A student must pitch a rainwater project to a mixed panel: engineers and city treasury staff.",
      "open with maintenance costs for treasury, then piping schematics for engineers, in five minutes total",
      ["recite the same pitch to the whole panel", "lead with ten minutes of scenery photos", "skip the cost model as too boring"]),
    c("qualified claim", "saying exactly what you know, and marking what you do not",
      "This fix covers our three test cases; the edge cases need a week — and the client trusts the estimate.",
      ["claiming certainty about everything to sound strong", "hiding limitations until after payment", "saying maybe on every line to stay safe"],
      "An engineer reports sensor findings to a board that wants one clean number.",
      "give the range with confidence bounds and one sentence on what would change it",
      ["round to a confident single figure for effect", "present all forty pages raw with no summary", "refuse any number without five years of data"]),
    c("consistency appeal", "reminding people of their own stated commitments",
      "You said punctuality matters here — and the late manager adjusts, not to a rule, but to his own words.",
      ["quoting rules the person never accepted", "shouting commitments they never made", "threatening punishment for every small slip"],
      "A volunteer coordinator must bring no-shows back without shaming them.",
      "reference each volunteer's own signup reason and offer a role that fits their stated why",
      ["post a wall of shame for absentees", "assign the no-shows to the worst shifts", "text the entire group about one person"]),
    c("storytelling with evidence", "carrying one true case, then anchoring it to the data",
      "One repaired classroom, then the district-wide repair stats — and the board funds the whole program.",
      ["telling a moving story with no data at all", "dumping only spreadsheets with no human case", "inventing a child's story for dramatic effect"],
      "An NGO must persuade a donor to fund laptop labs.",
      "follow one named student's real results with the cohort's measured gains and unit costs",
      ["screen a dramatic film and skip all figures", "show thirty charts with no names at all", "present a composite child as one real student"]),
    c("calibrated questions", "asking precise questions that surface the other side's real constraints",
      "What makes June hard for delivery? — the vendor reveals the holiday crunch, and the plan shifts to May.",
      ["asking any concerns and then moving on", "interrogating with yes-or-no traps", "avoiding all questions to seem decisive"],
      "A buyer must learn why a supplier resists a price cut without damaging the relationship.",
      "ask which input costs moved and what volume would unlock the old rate",
      ["threaten to switch suppliers in the first minute", "accept the first no and end the talks", "demand the supplier's full cost sheet publicly"]),
    c("ethical reciprocity", "giving real value first so cooperation feels natural, never owed",
      "The consultant shares one free fix, and the client asks — unprompted — about a retainer.",
      ["keeping score of favors to demand returns", "giving gifts only to trap a sale", "refusing to share anything before payment"],
      "A software vendor wants trust in a skeptical market.",
      "publish a free tier that is genuinely useful, with paid limits stated up front",
      ["send free trials that auto-convert to paid", "gate every tutorial behind a sales call", "mail logo pens, then invoice marketing support"]),
    c("concession timing", "planning when and what to yield, so trade-offs stay visible",
      "The seller holds price but adds free delivery; both sides see exactly what moved, and the deal closes.",
      ["yielding everything at the first silence", "refusing to move an inch on any point", "trading points secretly, one conversation at a time"],
      "A project manager faces a client who wants just one more feature, repeatedly.",
      "keep a visible scope board where every addition trades a date or a feature, agreed in writing",
      ["accept all extras and quietly slip every deadline", "refuse all extras with no explanation at all", "promise the feature verbally and never log it"])
  ],
  "HOW TO BECOME UNSTOPPABLE": [
    c("deliberate practice", "focused repetition at the edge of your skill with fast feedback",
      "Ria drills only her weakest chords for twenty minutes daily, recording and correcting, never replaying favorites.",
      ["repeating what you already master for hours", "practicing while distracted by shows", "waiting for inspiration to strike"],
      "A chess trainee plateaus at blitz games; the coach must design real improvement in forty-five minutes a day.",
      "review each loss's key mistake, drill that pattern fifteen minutes, then test it in one timed game",
      ["play twenty more blitz games for volume", "memorize opening trivia with no review", "watch streams for the full session"]),
    c("feedback loop", "acting, measuring, adjusting, then repeating with real signals",
      "Every Friday, Ben checks his email templates' reply rates and rewrites the worst performer.",
      ["guessing what worked with no data at all", "changing five things at once so nothing is learnable", "ignoring results to protect your feelings"],
      "A baker's new bread sells unevenly across the week; she must fix supply without waste.",
      "track daily sales per bread, adjust one variable weekly, and log each change's effect",
      ["bake by mood each morning", "change flour, price, and timing all at once", "copy the rival bakery's mystery recipe"]),
    c("process goals", "goals you fully control through your own actions",
      "Write three hundred words daily survived the chaotic month; finish the novel by June did not.",
      ["setting goals that depend on other people's decisions", "vowing outcomes you cannot directly cause", "having no goals at all and drifting"],
      "A novice runner fixates on a medal; the coach must anchor her plan in controllable work.",
      "set weekly run counts and drill minutes, treating race time as an outcome to check, not chase",
      ["check the leaderboard every hour", "train only when motivation peaks", "guarantee a podium publicly before training"]),
    c("priority management", "choosing the few tasks that move everything else",
      "Each morning Ada marks the one task that unlocks the rest, and it goes first, before any inbox.",
      ["doing the easiest tasks first every single day", "treating every task as equally urgent", "keeping every option open forever"],
      "A team lead drowns in tickets; the supervisor must restore focus without stalling work.",
      "rank tickets by blocker impact, cap work-in-progress at three, and review the ranking daily",
      ["sort tickets by who shouted loudest", "assign every ticket to everyone equally", "freeze all tickets for a thinking week"]),
    c("time blocking", "giving each important task its own reserved slot on the calendar",
      "Deep work 8 to 10, reviews 10 to 11, admin after lunch — the day finally stops leaking.",
      ["filling the calendar with meetings only", "keeping the whole day unscheduled for flexibility", "blocking sleep hours for extra work"],
      "A thesis student keeps losing research time to chores and chats.",
      "reserve two fixed morning library blocks with the phone in a locker, and shift chores to set windows",
      ["study whenever free in the evening", "reply to each chat the minute it lands", "move the blocks around daily to stay fresh"]),
    c("weekly review", "a fixed session to close loops and plan the next week deliberately",
      "Sunday at six: Mia empties her inbox, checks project lists, and sets three outcomes for the week.",
      ["reviewing only when a crisis forces it", "planning every minute of the next month", "skipping the review whenever the week went badly"],
      "A shop owner juggles orders and staff; the advisor installs a sustainable rhythm.",
      "hold a thirty-minute Monday review of stock, rota, and the week's three priorities on one page",
      ["hold a four-hour meeting every Monday", "review nothing and fight fires by phone", "review only during December inventory"]),
    c("commitment device", "a pre-set mechanism that locks in your future choice",
      "Lito hands his game controller to a friend until Friday; wanting it back is not enough to get it.",
      ["writing promises in a diary nobody sees", "relying on remembering your motivation later", "setting reminders you can swipe away"],
      "A freelancer must stop skipping invoice day or cash flow dies.",
      "auto-schedule invoice drafts and give the accountant authority to send them each Friday",
      ["stick a motivational note on the monitor", "promise himself this week for sure", "move invoice day whenever a client asks"]),
    c("progress metric", "one visible number that proves movement on what matters",
      "The wall chart's streak of completed morning sessions outlasted every motivational video.",
      ["counting twenty vanity numbers nobody reads", "hiding all progress so no one gets jealous", "measuring only outcomes you cannot control"],
      "A literacy program must show tutors their real impact weekly.",
      "track each learner's reading speed weekly and post class medians beside the tutor's session count",
      ["count total posters printed as impact", "assess reading only once a year", "report only feelings-based vibe checks"]),
    c("goal gradient", "effort rises as the finish line comes into view",
      "The loyalty card's two pre-filled free stamps doubled completions — people finish what feels started.",
      ["starting every project from a blank page with no visible progress", "hiding how much of the task remains", "making every task feel endless and identical"],
      "A city wants residents to finish long permit forms online.",
      "show a progress bar pre-marked with the fields already auto-filled from city records",
      ["add a welcome survey before the form", "display all forty sections as one page", "reset all progress if any single field is wrong"]),
    c("recovery discipline", "treating rest as scheduled training, not weakness",
      "The athlete's plan lists sleep at ten and a nap after drills — right beside the sprint sets.",
      ["training harder on every tired day", "saving all rest for after the season", "replacing sleep with extra repetitions"],
      "A quiz team must peak for nationals in six weeks without burning out.",
      "plan deload days, fixed sleep windows, and a taper week before the event",
      ["add daily all-nighters in week six", "quiz the team straight through meal breaks", "schedule the mock championship after the real one"])
  ]
};

const advanced = {
  "MIND MANIPULATIONS": [
      c("DARVO", "an offender denying, attacking the accuser, and reversing victim and offender",
        "Caught copying work, Ren declares himself the real victim of an accusation campaign and files a counter-complaint the same day.",
        ["calmly denying an accusation and asking for evidence", "reporting real harassment through proper channels", "apologizing first while the facts are still being checked"],
        "A team lead receives a DARVO counter-complaint right after documenting clear plagiarism and must protect both fairness and the reporter.",
        "keep the documented evidence central, hear each party separately, and rule on records rather than volume",
        ["side with the louder complaint to close the conflict fast", "drop both cases and warn everyone to just get along", "punish the reporter for upsetting the accused"]),
      c("bait-and-switch", "advertising an attractive deal to draw people in, then substituting a worse one",
        "The flyer's cheap laptop is suddenly out of stock the moment customers arrive, and only the pricey models get pushed.",
        ["selling out a real deal and posting an honest restock date", "upgrading a customer free when their item runs out", "raising prices in a true shortage with a public notice"],
        "A regulator drafts rules so that any promo item shown in ads must actually be obtainable.",
        "require advertised stock to exist, publish rain-check terms, and penalize fake out-of-stock flags",
        ["let each store define availability however it likes", "ban all discounts so no switching can ever occur", "require only that the advertisement look attractive"]),
      c("intermittent reinforcement", "rewarding unpredictably so the behavior becomes hardest to stop",
        "A slot machine pays at random moments, so players keep pulling far longer than under any fixed payout schedule.",
        ["paying a fixed salary on the same date monthly", "rewarding every correct answer in a tutoring drill", "stopping all rewards the moment behavior improves"],
        "An app designer must keep users engaged without using compulsive random-reward loops.",
        "use transparent earned milestones, and state the real odds for any random bonus",
        ["randomize loot drops and hide the odds from users", "punish skipped days, then reward heavily at random", "send rewards only when usage dips, at random hours"]),
      c("moving the goalposts", "changing the demanded standard each time the previous one is met",
        "Cleo hit the ten sales target, then heard sales alone were never the real measure, and now faces new conditions weekly.",
        ["updating public targets once a year with clear notice", "revising plans because requirements truly changed, with reasons shared", "asking for one extra small favor once a year"],
        "An HR officer must design performance reviews that managers cannot quietly shift mid-cycle.",
        "freeze criteria in writing at cycle start and require signed approval for any mid-cycle change",
        ["let managers adjust targets verbally whenever results improve", "score employees on overall impression alone each year", "rotate targets secretly so no one can compare notes"]),
      c("negging", "opening with deliberate backhanded remarks to lower a person's confidence",
        "A stranger opens with a remark that she is almost too pretty to be this slow, then waits for the sting before flattering.",
        ["giving honest constructive criticism when it was asked for", "joking warmly with an old friend who enjoys the banter", "respectfully disagreeing about a film's plot"],
        "A community moderator must write rules against disguised put-downs without banning all criticism.",
        "ban remarks aimed at undermining confidence on first contact while allowing topic-based critique",
        ["ban every negative word anywhere in chat", "make new-member channels praise-only forever", "ignore tone completely and punish only slurs"]),
      c("manufactured urgency", "inventing fake deadlines or crises to force rushed decisions",
        "A caller warns that the system shuts in ten minutes and the fee must be paid now, though no such cutoff exists anywhere.",
        ["announcing a genuine deadline together with its real reason", "expediting a true critical outage with paid overtime", "planning tasks by real priority and due dates"],
        "A sales policy must create honest urgency for real promotions only.",
        "allow urgency claims only when a dated, verifiable event backs them, with manager sign-off",
        ["script a today-only pressure line for every call", "forbid all deadlines so sales slow to a crawl", "let agents invent one fake deadline per day, capped"]),
      c("illusion of choice", "presenting options so that every path serves a hidden goal",
        "A survey asks whether the fee should rise five or eight percent, and never whether it should rise at all.",
        ["laying out pros and cons across genuinely different options", "letting a committee pick from open proposals", "abstaining from a vote you honestly find unfair"],
        "A product manager must gather honest feature votes rather than steer them.",
        "include a none-of-these option and a free-text field, then publish the raw tallies",
        ["offer only the two features leadership already prefers", "close the vote early once the favored option leads", "weight manager votes five times heavier, quietly"]),
      c("projection", "accusing others of your own hidden behavior to deflect suspicion",
        "A chronic gossip warns everyone about a supposed blabbermouth, yet every traced tale leads back to the accuser.",
        ["naming a real repeated pattern with concrete examples", "sharing your own feelings inside a trusted circle", "asking someone directly whether a rumor is true"],
        "A mediator suspects projection in a dispute but must stay fair without diagnosing anyone.",
        "compare every accusation against logged behavior and timestamps before weighing the claims",
        ["assume the loudest accuser is simply the honest one", "treat both parties as equally guilty without records", "label the accuser a projector in the open meeting"]),
      c("coercion disguised as help", "offering assistance structured so that refusing becomes costly",
        "A landlord offers to handle the tenant's paperwork, then holds the tenant's own documents until the lease is renewed early.",
        ["lending a tool and asking for it back on time", "hiring an assistant the client chose freely", "teaching a skill so a person needs less help later"],
        "A nonprofit designs a lending program so that help never becomes a leash.",
        "leave borrower documents with the borrower, publish all terms, and route disputes to an independent office",
        ["let staff hold originals for safekeeping until repayment", "attach quiet processing fees to each favor", "make continued aid depend on supporting the board's slate"]),
      c("astroturfing", "faking grassroots support to make a product or cause seem popular",
        "Hundreds of brand-new accounts post identical praise for a failing product within the same hour.",
        ["inviting real customers to an honest review event", "publishing verified-purchase reviews with disclosure", "answering criticism with data and receipts"],
        "A platform must curb fake grassroots campaigns without punishing genuine fans.",
        "detect coordinated posting patterns, require paid-campaign disclosure, and label suspect clusters for review",
        ["delete every positive post about flagged products", "ban all new accounts during campaign season", "allow paid posters who vary their punctuation"])
  ],
  "SELF RESILIENCE": [
    c("stress inoculation", "building tolerance by facing graded doses of a stressor with skills attached",
      "Before public speeches, Em rehearses to one friend, then ten, then a hall, adding a calming routine at each step.",
      ["throwing someone into the biggest crowd with no training", "avoiding all rehearsal until the real event", "practicing only in the most comfortable setting forever"],
      "A pilot trainee freezes on radio calls; the instructor must design progressive exposure safely.",
      "script the standard calls, drill them solo, then add a live frequency, then busy airspace — with debriefs",
      ["send the trainee straight into a busy control zone", "ban radio practice until the check-ride", "reassure without ever touching a microphone"]),
    c("psychological flexibility", "holding plans loosely enough to act on your values as situations change",
      "When a storm cancels the outdoor wedding, Coco rearranges the day around what mattered: family and vows, not the venue.",
      ["changing your core values to match each crowd", "refusing to alter any plan regardless of facts", "drifting with whatever others decide"],
      "A project's core feature is blocked; the lead must adapt without abandoning the mission.",
      "restate the mission, offer two honest paths to it, and let the team choose with clear trade-offs",
      ["cancel the project since plan A failed", "pretend nothing changed and force plan A", "switch goals weekly with the team's mood"]),
    c("cognitive defusion", "seeing thoughts as passing mental events rather than commands",
      "Instead of obeying the thought I can't do this, Wally notes that he is having that thought, and starts the first rep.",
      ["arguing until a thought disappears forever", "believing every thought equally deserves action", "suppressing thoughts so they never return"],
      "An athlete is flooded by self-critical thoughts mid-game; the coach wants focus, not a therapy debate.",
      "teach a quick label-and-return routine: name the thought, breathe, return to the next play",
      ["ban negative talk with push-up penalties", "analyze every thought aloud during play", "scold the athlete for losing focus"]),
    c("distress tolerance", "surviving sharp distress in the moment without making things worse",
      "Fighting the urge to send an angry text, Luz holds an ice cube, counts breaths, and waits out the spike before choosing.",
      ["acting on every urge to release pressure", "needing to feel fully calm before doing anything", "avoiding all discomfort by leaving every room"],
      "A debtor faces collection calls; the counselor must prevent panic decisions while fixing finances.",
      "script one holding response for calls, set a fixed weekly money session, and list worst-case safeguards",
      ["advise ignoring all letters and calls forever", "encourage a new loan to silence collectors now", "tell the debtor to answer everything immediately"]),
    c("explanatory style", "the habitual way you explain good and bad events to yourself",
      "After a lost match, Ravi says the keeper was brilliant today and he will train penalties — not that he always loses.",
      ["praising yourself after every single event", "blaming all failures on other people", "believing outcomes never have causes at all"],
      "A sales team slumps after losses; the manager wants accurate, changeable explanations.",
      "in reviews, split outcomes into specific, changeable causes and log the next adjustment per rep",
      ["repeat that everything happens for a reason and close", "rank reps by optimism scores alone", "blame the market and end the meeting"]),
    c("self-distancing", "coaching yourself from a step-back view, as if advising a friend",
      "Before a hard talk, Ilang writes advice to herself in the third person and reads it once before entering.",
      ["dissociating so completely that you feel nothing", "avoiding reflection by staying constantly busy", "asking others to decide everything for you"],
      "A founder must decide on a co-founder buyout while emotionally flooded.",
      "draft the decision memo as advice to a founder in your exact shoes, sleep once, then decide",
      ["decide within the argument thread immediately", "poll the whole staff for a verdict", "flip a coin to escape the feelings"]),
    c("post-traumatic growth", "positive change some people find after wrestling with hard events",
      "After a house fire, Dan organizes a block fire-drill network and says the scare reordered what matters.",
      ["claiming tragedy is worth it or a gift", "requiring trauma for any growth at all", "forcing victims to find silver linings on demand"],
      "A support-group facilitator must honor grief while leaving room for growth talk.",
      "let members set the frame, reflect growth only when they name it, and keep grief fully valid",
      ["open every session asking for the gift in the loss", "correct members who see no upside", "end meetings early if tears appear"]),
    c("hardiness", "a stance of commitment, control, and challenge toward stressors",
      "Facing a plant closure, Sol maps what she controls, stays engaged with coworkers, and treats reskilling as a challenge.",
      ["denying that the event changes anything at all", "controlling other people to feel secure", "avoiding every challenge to stay safe"],
      "An HR program must build resilience before a big reorganization.",
      "run workshops sorting concerns into controllable, influenceable, and accept, with one owned action each",
      ["broadcast reassurances and skip the workshops", "let employees redesign the whole reorganization", "offer only a stress hotline leaflet"]),
    c("resonance breathing", "slow, even breathing near six breaths per minute that steadies the body",
      "Before results are posted, Pia breathes in for five and out for five for two minutes, and her hands settle.",
      ["holding your breath as long as possible", "breathing as fast as you can to refresh", "pacing breaths only during panic, never before"],
      "A test-prep class needs a brief, legitimate calm-down routine before exams.",
      "practice paced breathing two minutes daily, then once before the exam doors open",
      ["breathe into a paper bag before tests", "skip practice and try pacing only mid-panic", "run sprints right before entering the hall"]),
    c("values clarification", "naming what truly matters so choices line up with it",
      "Offered a bigger title, Jai lists his top values — family time, craft mastery — and declines the role that kills both.",
      ["copying a friend's values because they seem popular", "listing only what others expect of you", "treating every value as equally strong forever"],
      "A career coach must help a burnt-out nurse decide without imposing an answer.",
      "sort cards of what matters, rate current job fit, and design two experiments that test the top values",
      ["tell the nurse to quit because burnout means quit", "assign the coach's own favorite career path", "push a pay-only comparison table"])
  ],
  "CONVINCE OTHERS": [
    c("motivational interviewing", "drawing out a person's own reasons for change instead of pushing yours",
      "What would be better if you stopped? — the patient argues for the change himself and books the follow-up.",
      ["lecturing until the listener surrenders", "listing everyone else's failures as warnings", "pressing for commitment in the first minute"],
      "A clinic wants diabetic patients to stick to meal plans; compliance lectures have failed.",
      "train staff to ask for the patient's own why, reflect it, and let the patient set the first small step",
      ["show graphic complication photos at intake", "fine patients for missed diet targets", "hand out standard printouts with no conversation"]),
    c("Socratic questioning", "guided questions that let someone test their own reasoning",
      "What would prove that plan wrong? — the analyst finds the missing cost case herself and revises it.",
      ["asking questions to trap and humiliate", "endless questions with no direction at all", "feeding the answer and calling it discovery"],
      "A mentor must correct a junior's risky investment thesis without ordering a change.",
      "ask for the thesis's failure conditions, data sources, and what a rival analyst would attack first",
      ["declare the thesis wrong and assign reading", "poll the team to vote the idea down", "rewrite the junior's memo silently overnight"]),
    c("steelmanning", "restating the opposing case in its strongest form before replying",
      "Your strongest point is the downtime risk — and the vendor, feeling heard, discloses the real failure stats.",
      ["twisting the opponent's words into a weaker version", "repeating their weakest sentence on loop", "skipping their argument entirely to rebut"],
      "A council hearing on a bike lane is polarized; the chair wants a usable record.",
      "have each side restate the other's best point to its owner's satisfaction before rebuttals begin",
      ["cap each side to angry slogans for television", "let each side restate the weakest quote only", "skip restatement and call the vote early"]),
    c("attitude inoculation", "exposing a weak form of a counterargument early so it loses power later",
      "The teacher presents a mild version of a scam pitch, students refute it, and later they spot the real one instantly.",
      ["banning all mention of the opposing idea", "exposing students to the strongest attack with no rehearsal", "repeating slogans with no challenge at all"],
      "A bank must prepare customers for voice-clone family-emergency scams.",
      "send a sample fake-emergency script, walk through the tells, and drill one safe verification phrase",
      ["advise never trusting calls, with no drill", "post one warning poster in the lobby", "promise reimbursement to remove all caution"]),
    c("central-route persuasion", "changing minds through real argument quality, not surface cues",
      "The engineer wins the vote with failure math and test logs, while the rival's celebrity video falls flat.",
      ["winning votes with famous endorsers alone", "polishing slides while hiding the numbers", "repeating a slogan until it feels true"],
      "A safety officer must convince management to fund a costly fix with lasting commitment.",
      "present incident costs, failure probabilities, and vendor quotes, and invite the auditor to check them",
      ["fly in a motivational speaker for the board", "print glossy posters of past accidents", "delay the numbers until after the budget vote"]),
    c("descriptive-norm messaging", "reporting what people actually do, accurately, to guide behavior",
      "Most guests reuse towels — a true logged 74 percent — and that beat help save the planet in the trial.",
      ["inflating the majority to manufacture pressure", "shaming the minority with fake lists", "hiding the real numbers to avoid debate"],
      "A city wants higher tax filing without lying about compliance.",
      "publish true district-level filing rates and send a nudge letter referencing them",
      ["claim 98 percent file already when 61 do", "name and shame last year's non-filers", "threaten audits in every sentence"]),
    c("message tailoring", "matching the message's values and identity to the receiver",
      "For the veteran, the stop-smoking leaflet leads with duty and crew; for the new mom, energy and years with her kids.",
      ["sending identical mass texts to all segments", "guessing identities from appearances alone", "changing the facts per audience"],
      "A vaccination drive must reach three distinct communities ethically.",
      "co-write three versions with local leaders, keep one fact sheet, and vary only frames and channels",
      ["translate the same flyer word for word only", "rent celebrities unknown to each village", "alter efficacy numbers per community"]),
    c("pre-suasion", "setting attention on what makes the coming message land best",
      "Before the pitch, the host asks how important reliability is, so the room weighs reliability when slides appear.",
      ["bribing the audience before the meeting", "hiding the agenda until after the vote", "lecturing on unrelated topics to waste time"],
      "A safety briefing must earn real attention in ten minutes without tricks.",
      "open with the crew's own near-miss reports, then link the new protocol to those events",
      ["start with a viral joke compilation", "schedule the briefing after the shift party", "read the manual aloud from cover to cover"]),
    c("BATNA framing", "knowing and calmly showing your best alternative so pressure fades",
      "We can build in-house by March — and the vendor reopens terms without a single threat being made.",
      ["shouting ultimatums you cannot execute", "inventing alternatives for the other side", "revealing your limits in the first five minutes"],
      "A school negotiates bus contracts and must not overpay, yet keep service stable.",
      "cost the parent carpool option honestly, mention it once factually, and price the contract against it",
      ["bluff a fake rival bus company quote", "accept the first renewal to avoid risk", "email parents threats to pull buses next week"]),
    c("commitment scaffolding", "structuring small public steps so big change becomes reachable",
      "The team sets one public weekly demo; by month three, the impossible migration is simply what they do.",
      ["demanding the full transformation overnight", "keeping all steps private and vague", "skipping checkpoints and hoping for the best"],
      "A gym must retain January joiners past March without shaming anyone.",
      "offer opt-in buddy check-ins and a visible four-week ladder of two sessions a week",
      ["post attendance rankings in the lobby", "sell twelve-month contracts with no follow-up", "call absent members daily at dawn"])
  ],
  "HOW TO BECOME UNSTOPPABLE": [
    c("identity-based habits", "building behavior from the person you choose to be, one proof at a time",
      "I am a runner — Lan runs two laps even on bad days, because that is what runners do.",
      ["waiting to feel like a runner before running", "chasing outcomes with no change in self-view", "copying a celebrity's exact routine blindly"],
      "A recovering gambler must rebuild routines; every lapse shatters his old self-story.",
      "define three I-am-someone-who anchors with tiny daily proofs and a lapse-recovery script",
      ["ban all money handling from day one", "track only total money saved as identity", "require perfect streaks or restart to zero"]),
    c("deep work", "uninterrupted concentration on a demanding task that compounds",
      "Two phone-free hours at dawn produce the chapter; ten scattered hours do not.",
      ["calling busywork deep focus", "multitasking through the hardest section", "scheduling depth only whenever free"],
      "An analyst's model keeps failing; the manager must protect thinking time.",
      "block a ninety-minute no-meeting window with calls held, and require one output per block",
      ["add a status meeting to discuss the model", "allow open chat during the block for questions", "move the block whenever anyone schedules over it"]),
    c("environmental design", "arranging surroundings so the good choice is the easy one",
      "Fruit on the table, phone charging in another room — willpower stops being the plan.",
      ["hiding snacks behind willpower posters", "blaming every slip on character alone", "making good habits harder to reach"],
      "A night-shift worker keeps missing gym sessions after work.",
      "pack the gym bag into the car before the shift and route home past the gym entrance",
      ["leave the bag at home to remember it", "store the gym shoes under old boxes", "plan workouts on the way past three bars"]),
    c("pre-mortem", "imagining the plan already failed, then fixing the causes first",
      "It is launch day and the plan flopped — why? The team lists five reasons and kills two before coding.",
      ["celebrating the plan before writing it", "punishing whoever voices failure scenarios", "doing it after launch as a blame hunt"],
      "A barangay flood drill must not fail the way last year's did.",
      "run a pre-drill session listing top failure causes, assign owners, and re-check one week before",
      ["copy last year's script unchanged", "skip the drill due to the weather forecast", "hold the pre-mortem after flood season"]),
    c("after-action review", "four honest questions after an event: intended, actual, why, and next",
      "The crew's twenty-minute review found the wrong radio channel — fixed before the next run.",
      ["reviewing only to find one person to punish", "skipping reviews after wins entirely", "collecting lessons that never reach the plan"],
      "A sales team closes its first big enterprise deal and must learn from it.",
      "hold a one-hour review with a timeline, decisions, and two process changes owned by named people",
      ["celebrate and rush to the next deal", "write a forty-page report nobody reads", "review only the lost deals"]),
    c("mental contrasting", "pairing the goal with the real obstacles, then plans for each",
      "Wish, outcome, obstacle, plan: I want the license; the exam is at dawn; I sleep late; so the phone sleeps in the kitchen.",
      ["visualizing only the success scene", "listing obstacles with no plans attached", "focusing only on what could go wrong"],
      "A first-time entrepreneur plans a launch while working nights.",
      "write wish, outcome, obstacle, and plan for capital, time, and energy, each with one if-then response",
      ["storyboard the victory party in detail", "list fifty risks and freeze in place", "skip the obstacle step to stay positive"]),
    c("instructional self-talk", "coaching yourself with task cues instead of judgment",
      "Elbow in, eyes level beats don't choke on every free throw.",
      ["shouting that you are a loser to spark effort", "cheering with no technical cue at all", "repeating vague be-confident phrases"],
      "A call-center rookie shakes on hard calls; the trainer installs a cue card.",
      "script three move cues — slow, name, next step — and rehearse them into two mock calls daily",
      ["lecture the rookie on toughness", "play motivational clips between calls", "forbid all self-talk as a distraction"]),
    c("energy management", "scheduling by your real energy curves, not just hours",
      "Ruth writes at her 6 a.m. peak, holds meetings at the 2 p.m. dip, and reviews at night.",
      ["treating every hour as identical", "filling peak hours with small-talk tasks", "running on caffeine through every trough"],
      "A programmer must ship a compiler feature in a month on a fixed forty-hour week.",
      "reserve 9 to 11 for compiler work, batch reviews at 4, and log energy for two weeks to tune",
      ["fill mornings with agile ceremonies", "schedule the hard part after dinner daily", "promise weekends if it slips"]),
    c("friction engineering", "deliberately adding or removing steps to steer your own behavior",
      "Logging out of shopping apps and saving the store cart cut impulse buys to zero.",
      ["adding steps only to good habits", "trusting memory to resist every time", "removing every obstacle including safety checks"],
      "A student must cut doomscrolling during thesis season.",
      "move social apps off the home screen, set a twenty-minute nightly window, and log in manually",
      ["delete the thesis files to remove stress", "keep notifications on just in case", "hold a twenty-four-hour feed marathon as a detox"]),
    c("kaizen", "tiny, continuous improvements compounding over the long run",
      "The line saved one screw per unit weekly; by December the station led the plant.",
      ["waiting for one giant overhaul next year", "changing everything at once every week", "rejecting small fixes as not worth it"],
      "A sari-sari store's stocktaking eats a whole Sunday.",
      "count one shelf each weekday evening for ten minutes and reconcile the same day",
      ["close the store every Sunday for full counts", "buy inventory software before counting at all", "count only when the tax letter arrives"])
  ]
};

module.exports = { foundational, advanced };
