/*
 * SCIENCE concept library for the Geon GameHub questioner rebuild.
 * foundational = PREVIOUS questioner, advanced = NEW questioner.
 */
"use strict";

const c = (term, def, cue, misconceptions, setup, right, wrongs) =>
  ({ term, def, cue, misconceptions, setup, right, wrongs });

const foundational = {
  "SOLID, LIQUID, GAS": [
    c("a solid", "a state of matter that keeps its own shape and volume because its particles are locked in place",
      "A metal cube stays a cube whether it sits in a big box or a small box — its particles only vibrate in place.",
      ["a state whose particles fly apart to fill any container", "a state that flows and takes the shape of its container", "a state that exists only at very high temperatures"],
      "A warehouse must stackIdentical metal blocks tightly in a truck without any container shaping them.",
      "stack them directly — each block already keeps a fixed shape and volume on its own",
      ["pump them in as a fluid so they take the truck's shape", "heat them until they spread evenly through the truck", "shake the truck until the blocks fill every corner"]),
    c("a liquid", "a state of matter that keeps its volume but flows to take the container's shape",
      "Juice poured from a bottle into a flat dish spreads into the dish yet keeps exactly the same volume.",
      ["a state that keeps a fixed shape no matter the container", "a state with neither fixed volume nor fixed shape", "a state whose particles are bonded in a rigid lattice"],
      "A delivery firm must move one liter of cooking oil from a tall jar into a wide pan without losing any.",
      "pour it — the oil keeps its full volume while matching the pan's shape",
      ["compress it to a tenth to fit any container", "freeze it solid so it never matches the pan", "evaporate it and ship it as vapor"]),
    c("a gas", "a state of matter that expands to fill any container because its particles move freely",
      "Perfume released in one corner of a room soon reaches every corner — its particles spread through all the space.",
      ["a state locked into a fixed volume and shape", "a state that only fills the bottom of its container", "a state whose particles never leave their positions"],
      "A balloon is inflated in a corner of a sealed room, and its scent must reach a listener by the door.",
      "release it — the gas spreads by itself through the whole room",
      ["pour it so it flows along the floor only", "freeze it to the corner and wait", "shake the room so the gas slides to the door"]),
    c("melting", "the change from solid to liquid as heat is added",
      "An ice cube left in warm juice slowly turns to liquid and mixes in.",
      ["a liquid turning solid as heat leaves it", "a solid turning straight to gas without a liquid stage", "a gas turning to liquid as it cools"],
      "A snack stall needs its block of frozen juice ready to pour by noon, starting solid at dawn.",
      "leave the block at room temperature so steady heat melts it to liquid",
      ["place it in the freezer to speed the change", "leave it uncovered in the sun to turn directly to vapor", "shake it hard until it turns to gas"]),
    c("freezing", "the change from liquid to solid as heat is removed",
      "Water left in the freezer overnight turns into a solid ice tray.",
      ["a solid turning to liquid as heat is added", "a liquid turning to gas at its surface", "a gas settling into a solid on a cold surface"],
      "A fish vendor wants melted ice restored to solid ice packs for tomorrow's market.",
      "place the water trays in the freezer so heat leaves and the water solidifies",
      ["boil the water to make it solidify faster", "leave the trays in warm sunlight", "blow hot air across the trays until they harden"]),
    c("evaporation", "the change from liquid to gas at the surface, even below boiling",
      "A wet floor dries without ever bubbling — water leaves the surface quietly as vapor.",
      ["a liquid turning to gas only at its boiling point throughout", "a gas turning to liquid on a cold mirror", "a solid turning to liquid under gentle heat"],
      "Mopped hospital floors must be dry by morning without heat damage to the wax.",
      "leave the doors open overnight so the thin water layer evaporates on its own",
      ["flood the floor to rinse the water away", "cool the floor until the water turns solid", "cover the floor with plastic to hold the moisture in"]),
    c("condensation", "the change from gas to liquid as the vapor cools",
      "Cold soda taken from the fridge gathers water droplets on the can as air moisture cools on its surface.",
      ["a liquid turning to gas as it warms", "a solid turning straight to gas in open air", "a liquid turning to solid in a freezer"],
      "A cold-water pipe in a humid kitchen is dripping all over the counter.",
      "fit an insulating sleeve so the pipe surface stays warm and vapor stops condensing on it",
      ["heat the pipe so the drips evaporate faster", "wrap the pipe in ice to freeze the drips", "drill drain holes along the pipe"]),
    c("sublimation", "the change from solid straight to gas without passing through liquid",
      "Dry ice left in open air shrinks away as fog without ever forming a puddle.",
      ["a solid melting to liquid before turning to gas", "a gas turning straight to solid on a cold surface", "a liquid turning to vapor at the surface only"],
      "A stage crew needs dramatic fog without wet puddles on the electric stage floor.",
      "use dry ice so the solid sublimates straight to fog with no liquid stage",
      ["melt regular ice into a shallow pool of water", "boil a kettle of water beside the stage", "spray liquid water above the lights"])
  ],
  "TRANSLATIONAL MOTIONS / ROTATIONAL MOTIONS": [
    c("translational motion", "motion in which every point of the object moves along the same path",
      "A crate slides straight across a smooth floor — every point of it traces the same forward line.",
      ["motion where the object spins about a fixed line", "motion that repeats at regular time intervals", "motion along a circular path about an outside point"],
      "A warehouse robot must carry a pallet so that the load never tilts or spins on its base.",
      "drive the base in straight equal steps so every point of the pallet shares one path",
      ["spin the pallet about its center post while moving", "swing the pallet like a pendulum along the aisle", "roll the pallet over and over along the floor"]),
    c("rotational motion", "motion in which an object spins about a fixed line called an axis",
      "A ceiling fan's blades sweep circles around the central shaft while the hub stays in place.",
      ["motion where every point shares one straight path", "motion where the object simply falls straight down", "motion that moves the object to a new place with no turning"],
      "A pottery teacher wants students to shape clay evenly on a wheel that stays in one spot.",
      "spin the wheel about its fixed central axis so the clay turns in place",
      ["slide the wheel across the bench while shaping", "bounce the wheel gently up and down", "carry the wheel around the room as it shapes"]),
    c("axis of rotation", "the fixed line around which a spinning body turns",
      "A door swings around the line through its two hinges, and every point turns about that line.",
      ["the path along which an object slides forward", "the point where a falling object lands", "the line a rolling ball travels along"],
      "A technician mounts a heavy inspection lamp so it can swing to any angle without drifting across the desk.",
      "fix it on a hinge pin so the lamp rotates about that single line",
      ["hang it on a rubber band so it drifts freely", "rest it on rollers so it slides when pushed", "float it on an air table so any touch moves it"]),
    c("linear speed", "the distance traveled per unit of time along a path",
      "A jeepney covers 40 kilometers in one hour of highway travel — that rate is its speed along the road.",
      ["the number of full turns completed per minute", "the angle swept out in a given time", "the force needed to start an object moving"],
      "A delivery rider must report how fast the package is moving along the highway, not how the wheels spin.",
      "report distance covered divided by travel time from the GPS log",
      ["report the tachometer's revolutions per minute", "report the angle the wheels have turned", "report the engine's torque output"]),
    c("rotational speed", "the number of turns an object completes per unit of time",
      "A hard-disk platter spinning at 7,200 revolutions per minute turns 120 times each second.",
      ["the distance covered per hour along a road", "the straight-line speed of a sliding box", "the time a pendulum needs to settle"],
      "A blender label must state how fast the blade assembly spins inside the jar.",
      "state the revolutions per minute of the blade axle",
      ["state the kilometers per hour of the blade tip", "state the liters the jar holds", "state the watts printed on the plug"]),
    c("rolling motion", "combined translation and rotation, as when a wheel turns while moving forward",
      "A car's wheel spins about its axle while the axle itself carries the car down the road.",
      ["spinning in place about a fixed axis only", "sliding forward with no turning at all", "swinging back and forth through a lowest point"],
      "A museum cart must move smoothly across the hall without scraping the wooden floor.",
      "fit it with wheels so each one turns while the axle advances",
      ["slide the cart on smooth plastic runners", "drag the cart on felt pads", "carry the cart on a spinning turntable"]),
    c("periodic motion", "motion that repeats itself at regular time intervals",
      "A pendulum clock's bob swings left and right, returning to each position at even intervals.",
      ["motion that slows and stops after one push", "motion in one straight line that never repeats", "motion that jumps at random moments"],
      "A demonstration bench needs a motion that recurs at a dependable interval for timing lessons.",
      "set up a pendulum whose swings repeat at a steady period",
      ["roll a ball until friction stops it", "slide a block down a ramp to the floor", "launch a dart once into a target"]),
    c("angular displacement", "the angle swept by a rotating line from its starting position",
      "A doorknob turned a quarter of the way from its rest position has swept a right angle.",
      ["the distance a cart slid along the floor", "the weight a shelf can carry", "the time a fan takes to stop spinning"],
      "A valve wheel must be reported as turned by a set amount from its closed mark.",
      "log the angle swept from the closed mark, in degrees or radians",
      ["log how far the wheel rim moved in meters", "log the wheel's weight in kilos", "log the minutes spent turning it"])
  ],
  "PASCAL'S PRINCIPLES": [
    c("Pascal's principle", "pressure applied to a confined fluid is transmitted equally in all directions",
      "Press one spot of a sealed water-filled bag and every part of the bag tightens at once.",
      ["pressure applied to a fluid grows weaker with distance", "fluid pressure only pushes downward in a container", "pressure in a fluid depends on the container's color"],
      "A garage lift designer needs the push at one small piston to arrive undiminished at a wide one.",
      "connect both pistons with one confined fluid so pressure transmits equally",
      ["fit valves so pressure fades along the pipe", "leave the fluid open to air so pressure escapes", "send the force mechanically by rope instead of fluid"]),
    c("hydraulic lift", "a small force on a narrow piston raising a heavy load on a wide piston",
      "One mechanic gently pushes a pedal-size piston, and a car weighing many times more rises on the wide piston.",
      ["a system where the wide piston must be pushed harder than the load", "a lift that raises cars by burning fuel under the platform", "a system that works only with compressible gases"],
      "A workshop must raise a 1,500-kilogram car using muscle power alone, safely and repeatably.",
      "install a hydraulic lift so pedal force on the small piston lifts the car on the wide one",
      ["rig a lever long enough to touch the ceiling", "inflate a hot-air bag under the car", "pull the car up by hand over a pulley"]),
    c("pressure formula", "pressure equals force divided by the area over which it acts",
      "The same push spreads over a sharp nail's tiny tip digs in, while over a wide board it does not.",
      ["pressure equals force times area", "pressure equals force minus area", "pressure stays fixed no matter the area"],
      "A safety poster must teach apprentices why wide straps, not thin cords, should carry heavy loads.",
      "explain pressure as force divided by contact area — wide straps cut the pressure",
      ["teach that weight alone decides damage", "teach that thinner cords spread force better", "teach that area has no effect on pressure"]),
    c("the pascal (Pa)", "the unit of pressure equal to one newton of force spread over one square meter",
      "A force of one newton pressing on a one-square-meter surface equals one pascal of pressure.",
      ["a unit naming one kilogram of mass", "a unit naming energy used per second", "a unit naming force alone, with no area"],
      "An instrument label must state pressure in proper SI units.",
      "mark the gauge in pascals, newtons per square meter",
      ["mark the gauge in newtons only", "mark the gauge in kilograms per liter", "mark the gauge in watts"]),
    c("a confined fluid", "a fluid sealed inside a container so applied pressure cannot escape",
      "A capped syringe full of water feels rock-solid when you squeeze — the liquid has nowhere to go.",
      ["any fluid open to the air in a basin", "a fluid that evaporates when pressed", "a fluid held only by a loose lid"],
      "A demo must show fluid pressure transmitting exactly, with no leaks weakening the effect.",
      "seal the syringe with a finger so the fluid is fully confined before pressing",
      ["leave the tip open so pressure vents out", "use a torn balloon full of water", "fill the syringe halfway with air only"]),
    c("an incompressible fluid", "a fluid whose volume barely changes under pressure, like the liquid in brakes",
      "Squeezing a sealed water bottle barely dents it — the water's volume hardly yields.",
      ["a fluid that shrinks greatly under small pressure", "a fluid that boils away when compressed", "a fluid that only works in open tanks"],
      "A brake designer must make pedal force arrive at the wheels without lag.",
      "fill the lines with an incompressible brake fluid so force passes at once",
      ["fill the lines with springy foam", "leave air pockets in the lines", "use a gas that squashes under the pedal"]),
    c("hydraulic brakes", "a braking system where pedal force is carried by fluid to clamp every wheel together",
      "One press of the pedal moves fluid through lines, and all four wheels grip at the same moment.",
      ["brakes that work by air drying out the pads", "brakes where only the front wheel ever responds", "brakes driven by stretching rubber bands"],
      "A car's four wheels must grip together the instant the driver presses the pedal.",
      "run fluid lines to all wheels so pedal pressure reaches each caliper equally",
      ["wire each wheel to grip in sequence, one per second", "fit brakes only on the rear axle", "connect the pedal to the wheels by loose cable"]),
    c("force multiplication", "the gain in force when fluid pressure acts on a much larger piston area",
      "A thumb-sized piston at 200 newtons per square centimeter can raise a palm-sized piston pushing far harder.",
      ["a loss of force whenever fluid systems are used", "a gain in force only when the small piston is wider", "a gain that appears without any pressure at all"],
      "A shop press must multiply a worker's 150-newton push into thousands of newtons of pressing force.",
      "press a narrow piston so the pressure acts on a wide master piston below",
      ["gear the press so the worker pushes the load directly", "lengthen the handle until the load floats", "reduce the wide piston until it matches the small one"]),
    c("perpendicular transmission", "fluid pressure pushes at right angles to every surface it touches",
      "Water in a pipe presses outward on the walls at right angles, not along the pipe's length only.",
      ["fluid pressure that pushes only in the direction of the pipe", "fluid pressure that pulls surfaces inward toward the fluid", "fluid pressure that ignores the walls entirely"],
      "A tank designer must predict which way the walls and floor feel the fluid's push.",
      "treat every wall and the floor as pushed at right angles by the fluid",
      ["compute pressure along the walls' length only", "assume only the lid feels any push", "assume the floor alone is pressed"]),
    c("hydraulic press", "a machine using fluid pressure to compress, shape, or stamp materials",
      "A workshop press flattens metal blanks between plates driven by fluid behind a wide piston.",
      ["a press that works by winding a hand crank only", "a machine that cuts using spinning blades", "a hammer that strikes by falling gravity alone"],
      "A fabrication shop must flatten soft metal blanks uniformly with controlled force.",
      "use a hydraulic press so fluid-driven plates squeeze each blank evenly",
      ["strike each blank with a hand mallet", "roll the blanks under a bicycle wheel", "heat the blanks until they slump flat"])
  ],
  "ARCHIMEDE'S PRINCIPLES": [
    c("buoyant force", "the upward push a fluid gives to any object placed in it",
      "A beach ball pushed underwater pushes back hard against your hands — the water shoves it upward.",
      ["a downward pull that grows with depth in water", "a sideways push that depends on the object's color", "a force that appears only in moving water"],
      "A pool game needs a light ball to return to the surface the moment divers let go.",
      "let buoyancy act — the water's upward push floats the ball back",
      ["tie the ball to the pool floor", "spin the ball so it stays submerged", "drain the pool before releasing the ball"]),
    c("Archimedes' principle", "the buoyant force equals the weight of the fluid the object displaces",
      "A block pushed into a full cup spills water; the spilled water's weight is the extra upward push you feel.",
      ["buoyant force equals the object's own weight always", "buoyant force equals the object's weight times its speed", "buoyant force grows with the object's color and shine"],
      "An engineer must predict the upward push on a submerged valve housing before choosing anchors.",
      "compute the weight of water the housing's volume displaces — that is the buoyant force",
      ["weigh the housing in air and use that as the push", "measure the housing's color and guess", "use the housing's price as the measure"]),
    c("floating condition", "an object floats when it is less dense than the fluid it rests in",
      "Cork rides high on water because cork packs less mass into each cubic centimeter than water does.",
      ["an object floats whenever it is heavy enough", "an object floats only if it is hollow and metal", "an object floats only in moving water"],
      "A lab class must predict which carved shapes will ride on water without trial and error.",
      "compare each shape's density with water's — the lighter ones float",
      ["float the heaviest shape because it displaces more", "test only the metal shapes", "float everything by adding salt to their cores"]),
    c("sinking condition", "an object sinks when it is denser than the surrounding fluid",
      "A steel marble drops straight down in water because steel packs far more mass per cubic centimeter.",
      ["an object sinks whenever it floats first", "an object sinks only if it is lighter than the fluid", "an object sinks only in hot liquids"],
      "A sorting machine must separate stones from wooden beads in a water channel automatically.",
      "let density decide — the denser stones sink and the beads ride off with the flow",
      ["sort by color as the stones sink faster", "boil the channel so nothing sinks", "freeze the channel and weigh each piece"]),
    c("displaced fluid", "the fluid pushed aside by an object placed in it",
      "Getting into a full bathtub makes water spill — your body pushed that water aside.",
      ["the fluid that vanishes when an object sinks", "the fluid that sticks to the object's surface only", "the fluid that stays fixed when anything enters"],
      "An overflow basin must measure the volume of an oddly shaped machine part by water.",
      "submerge the part and collect the water it pushes over the rim",
      ["float the part and time how long it drifts", "weigh the basin with no water at all", "measure the part's reflection in the water"]),
    c("apparent weight", "true weight minus the buoyant force — why objects feel lighter underwater",
      "A rock heavy in air feels light the moment it dips below the surface, though nothing was removed from it.",
      ["weight that truly vanishes underwater", "weight that doubles at the pool's deep end", "weight that changes with the water's temperature only"],
      "A diver must know why a heavy anchor chain lifts easily once submerged.",
      "subtract the buoyant push from the chain's true weight — the rest is the felt load",
      ["tell the diver the chain lost mass in water", "tell the diver water pressure adds lift evenly", "tell the diver lighter objects sink slower"]),
    c("density", "mass packed into each unit of volume, written as mass divided by volume",
      "Lead packs eleven kilograms into every liter — nearly twenty times water's packing.",
      ["mass spread over surface area", "weight divided by the object's color", "volume divided by time"],
      "A quality lab must check whether souvenir bars are pure lead or a cheap blend.",
      "measure mass and volume, then compute mass per unit volume and compare with pure lead",
      ["shine a light through each bar and judge", "weigh only and ignore the size", "count how loudly each bar rings"]),
    c("why ice floats", "ice is less dense than liquid water, so it rides above the surface",
      "Ice cubes gather at the top of a glass because freezing spaced water's molecules slightly apart.",
      ["ice floats because it is heavier than water", "ice floats because cold pushes objects up", "ice floats because of the glass's shape"],
      "A science show must explain, without numbers, why icebergs ride high instead of sinking.",
      "show that frozen water occupies more room per gram, so ice floats on its own melt",
      ["demonstrate with a metal iceberg model", "claim cold water is lighter than warm", "claim salt in the sea lifts all solids"])
  ],
  HISTORY: [
    c("Archimedes and the crown", "the ancient test where water overflow exposed whether a crown was pure gold",
      "Around 250 BC, a Syracusan thinker compared the water pushed aside by a crown and by equal gold to answer King Hiero's doubt.",
      ["a Roman officer who sank his own fleet to test gold", "a merchant who weighed crowns on a spring scale he patented", "a king who melted every crown yearly to check them"],
      "A museum panel must caption the crown episode accurately, without adding invented laboratory tools.",
      "caption it as a water-displacement comparison that exposed a substituted metal",
      ["caption it as an acid-dissolution test on the crown", "caption it as a color comparison under candlelight", "caption it as a spring-balance weighing contest"]),
    c("Torricelli's barometer", "the 1643 mercury tube experiment that first measured air pressure",
      "Evangelista Torricelli inverted a mercury-filled tube and found the column stood at a steady height, balancing the air's weight.",
      ["a water wheel that measured wind speed in towers", "a sealed bell that carried divers to the seabed", "a glass flask that made lightning in jars"],
      "A textbook sidebar must credit the first true measurement of atmospheric pressure, with the right year.",
      "credit Torricelli's 1643 inverted mercury tube as the first barometer",
      ["credit a 1643 rain gauge on a cathedral roof", "credit Torricelli's hot-air balloon flight", "credit a 1643 tide clock in Venice"]),
    c("Magdeburg hemispheres", "von Guericke's 1654 demonstration where evacuated hemispheres resisted teams of horses",
      "Otto von Guericke pumped the air from two matched copper bowls, and sixteen horses failed to pull them apart.",
      ["two glass lenses that burned sails at a distance", "two iron rings that repelled every magnet", "two bells that rang without being struck"],
      "A science festival must stage a famous proof of air pressure using pull-teams and simple gear.",
      "recreate the evacuated hemispheres so teams strain against the air's push",
      ["stage a vacuum cleaner lifting a bowling ball", "float boats on compressed air cushions", "spin a flywheel until its rope snaps"]),
    c("Pascal and Puy de Dôme", "the 1648 mountain experiment showing pressure falls with altitude",
      "Florin Périer carried a barometer up the slopes and the mercury column dropped as he climbed.",
      ["a mine descent where the mercury column rose a full meter", "a sea voyage that proved tides move the mercury", "a tower climb that proved mercury ignores height"],
      "An exhibit must pair an altitude barometer reading with the historical trial that proved the effect.",
      "display the Puy de Dôme ascent record beside a live altimeter barometer",
      ["display a diving-bell record from a lake floor", "display a desert record with rising mercury", "display a cave record with flickering mercury"]),
    c("Pascal's Treatise on the Equilibrium of Liquids", "the 1653 work that founded modern hydraulics",
      "Blaise Pascal set out how confined liquids carry pressure, laying the base for every hydraulic machine.",
      ["a ship's log of ocean current measurements", "a blacksmith's manual on hammer design", "a lens-grinder's notebook on curved glass"],
      "A library display must name the founding written work of hydraulics.",
      "feature Pascal's Treatise on the Equilibrium of Liquids, written in 1653",
      ["feature a nineteenth-century diver's memoir", "feature a Roman aqueduct repair ledger", "feature an alchemist's manuscript on quicksilver"]),
    c("Bernoulli's Hydrodynamica", "the 1738 book linking flow speed and pressure in moving fluids",
      "Daniel Bernoulli's volume showed that faster flow in a stream pairs with lower sideways pressure.",
      ["a chart book that mapped ocean salinity only", "a treaty on canal tolls and barge widths", "an atlas of river names across Europe"],
      "A physics corridor must honor the book that first tied fluid speed to pressure.",
      "mount a plaque for Hydrodynamica, published in 1738",
      ["mount a plaque for a 1903 wind-tunnel report", "mount a plaque for a Roman aqueduct survey", "mount a plaque for a 1738 star catalog"]),
    c("Galileo's falling bodies", "the shift to studying falling motion by measurement rather than argument",
      "Galileo timed balls rolling down grooved boards and found falling follows a measurable rule.",
      ["a balloon ascent that measured thin-air falling", "a cannon duel that settled falling speeds by range", "a clock trial that weighed falling feathers"],
      "A classroom wall must state what made falling motion finally clear to science.",
      "credit Galileo's inclined-plane timing for making falling measurable",
      ["credit Aristotle's ledger of natural places", "credit a single tower drop with no timing", "credit a feather-versus-coin lottery"]),
    c("Newton's Principia", "the 1687 book giving mechanics one mathematical foundation",
      "Isaac Newton's volume tied falling bodies and orbiting moons to the same laws of motion.",
      ["a sailor's handbook of knot tables", "a surveyor's almanac of land measures", "a glassmaker's recipes for telescope lenses"],
      "A lecture hall frieze must name the single book that unified terrestrial and celestial motion.",
      "engrave Philosophiae Naturalis Principia Mathematica, 1687",
      ["engrave a 1687 tide table for London", "engrave Newton's coinage report for the Mint", "engrave a 1687 comet pamphlet"])
  ]
};

const advanced = {
  "SOLID, LIQUID, GAS": [
    c("plasma", "an ionized gas that conducts electricity and often glows",
      "Inside a lit neon sign, gas particles carry charge and pour out colored light.",
      ["a liquid metal that cools into signs", "a frozen gas that lights under pressure", "a solid conductor shaped like a tube"],
      "A signage shop must pick a state of matter that both conducts and emits light steadily.",
      "run an ionized gas — plasma — through the tube so it glows and conducts",
      ["fill the tube with molten wax and heat it", "freeze the gas solid behind glass", "pack the tube with salt crystals"]),
    c("supercritical fluid", "a state beyond the critical point with gas and liquid traits at once",
      "Above its critical point, carbon dioxide flows like a gas yet dissolves like a liquid.",
      ["a solid that flows through pipes like honey", "a gas that can never pass through fine material", "a liquid that boils away the moment it is sealed"],
      "A decaf plant must strip caffeine using a fluid that penetrates beans like gas but dissolves like liquid.",
      "run supercritical carbon dioxide above its critical point through the bean beds",
      ["flush the beans with boiling salt water", "grind the beans with dry quartz sand", "wash the beans in liquid mercury"]),
    c("vapor pressure", "the pressure of a vapor in balance with its liquid at a given temperature",
      "In a sealed bottle of water, escaping molecules build a steady vapor push at the surface.",
      ["the push of air on the outside of the bottle", "the weight of the liquid resting on the base", "the pressure needed to freeze the liquid"],
      "A fuel-tank designer must know the push building above stored gasoline on a hot day.",
      "consult the fuel's vapor pressure at the storage temperature and rate the tank for it",
      ["weigh the fuel and divide by tank height", "measure the tank's paint color and guess", "assume vapor never builds in a sealed tank"]),
    c("triple point", "the single temperature and pressure where solid, liquid, and gas coexist",
      "In a special cell, water's ice, liquid, and vapor all hold together at one exact condition.",
      ["any temperature where ice and steam share a kettle", "the freezing point at sea level under open air", "the boiling point inside a pressure cooker"],
      "A calibration lab needs one fixed reference condition where three phases coexist for checks.",
      "seal a triple-point cell and read its one exact temperature and pressure",
      ["boil tap water in an open pot and log it", "freeze seawater and note the crust", "mix ice and salt and record the slush"]),
    c("kinetic molecular theory", "the model of matter as particles in constant motion whose energy sets temperature",
      "Warmer tea means faster-jostling molecules; cooler tea means slower ones — nothing else changed.",
      ["a claim that particles rest still when hot", "a rule that heat flows only through metals", "a model where temperature measures container size"],
      "A teacher must link felt temperature to particle behavior without equations.",
      "show that higher temperature means faster particle motion on average",
      ["say heat is a fluid soaking into objects", "say particles grow larger when warmed", "say temperature measures the air's color"]),
    c("diffusion", "particles spreading on their own from crowded to less crowded regions",
      "A tea bag dipped at one side soon colors the whole cup without any stirring.",
      ["particles carried only by shaking the cup hard", "particles sinking to the bottom in a day", "particles clumping together at one edge"],
      "A nurse must time how a disinfectant vapor reaches every corner of a closed cabinet unaided.",
      "rely on diffusion and allow idle time for the vapor to spread evenly",
      ["tilt the cabinet so vapor flows downhill", "cool the cabinet to pull vapor inward", "paint the walls to attract vapor"]),
    c("anomalous expansion of water", "water expanding as it cools below about 4°C, so ice floats",
      "A lake freezes from the top down because cooling water below four degrees swells instead of shrinking.",
      ["water shrinking steadily until it is frozen solid", "ice forming first at the lake bottom", "cold water always sinking below warm water"],
      "A pond ecologist must explain how fish survive under a winter ice sheet.",
      "note that surface water below four degrees expands and stays on top, insulating the fish below",
      ["claim fish migrate into the mud before winter", "claim ice sinks and buries the fish in warmth", "claim the lake drains dry before freezing"]),
    c("boiling point vs external pressure", "water boils below 100°C where outside pressure is lower",
      "On a mountain trek, tea boils in a shorter time but cooks slowly — the water boils cooler up high.",
      ["water boiling hotter at high altitudes", "water boiling at 100°C everywhere on Earth", "pressure having no effect on boiling at all"],
      "A mountaineering guide must explain why rice stays hard though the pot is boiling.",
      "explain that low outside pressure lets water boil cooler, so cooking needs a pressure lid",
      ["advise adding salt to force a harder boil", "advise boiling twice as long at the same low heat", "advise covering the pot with a wool sock"])
  ],
  "TRANSLATIONAL MOTIONS / ROTATIONAL MOTIONS": [
    c("angular velocity", "the rate of rotation measured in radians per second",
      "A compact-disc drive motor rated at steady radians per second spins the disc at a constant turning rate.",
      ["the straight-line speed of the disc's edge in meters per hour", "the number of songs stored on the disc", "the force pressing the disc into its tray"],
      "A lab motor's spec sheet must state turning rate in proper rotational units.",
      "state angular velocity in radians per second on the spec sheet",
      ["state the motor's mass in kilograms", "state the shaft's length in millimeters", "state the housing temperature in celsius"]),
    c("tangential speed", "the linear speed of a point on a spinning body, equal to angular velocity times radius",
      "On a merry-go-round, the outer horse travels farther per turn than the inner one, so it moves faster along its path.",
      ["the speed that is identical at every radius of a spinning disc", "the turning rate measured in revolutions per second", "the pull holding a rider toward the center"],
      "A park ride's outer ring riders report feeling a stronger rush than inner riders.",
      "explain that tangential speed grows with radius at the same spin rate",
      ["claim every seat moves identically regardless of radius", "claim the rush depends only on seat color", "claim inner riders orbit faster than outer ones"]),
    c("moment of inertia", "a body's resistance to spinning, depending on how its mass spreads from the axis",
      "A dumbbell with weights at its ends is harder to twirl than the same mass gathered at the middle.",
      ["the weight of an object measured on a scale", "the straight-line drag of a sliding crate", "the object's ability to float in water"],
      "A flywheel must smooth an engine's pulses using resistance to speed changes.",
      "fit a flywheel with mass spread far from the axle for high rotational resistance",
      ["use a hollow shell with mass at the hub only", "use a feather-light shaft with no rim", "use a tall thin rod balanced on its tip"]),
    c("torque", "the turning effect of a force, equal to force times its lever arm",
      "Pushing a wrench at its far end turns a stiff bolt far more easily than pushing near the nut.",
      ["the push needed to slide a box along the floor", "the speed gained per second while turning", "the heat produced by a spinning bearing"],
      "A mechanic must loosen a rusted wheel nut without adding dangerous extensions.",
      "apply steady force at the wrench's far end to gain turning effect safely",
      ["strike the wrench with a hammer at the nut", "press close to the nut with full weight", "pull the wrench outward along its shaft"]),
    c("rotational equilibrium", "the state where net torque is zero, so no angular acceleration occurs",
      "A balanced seesaw with unequal riders holds level because each side's turning effect cancels.",
      ["a state where both sides spin equally fast", "a state reached only when total weight is zero", "a state where the beam swings ever faster"],
      "A loading crane must hold its boom level with a heavy off-center pallet attached.",
      "shift the counterweight until turning effects on both sides cancel exactly",
      ["add speed to the motor until the boom steadies", "lock the brake and accept the tilt", "lengthen the cable on the heavy side"]),
    c("conservation of angular momentum", "a spinner speeds up as its mass pulls inward when no outside torque acts",
      "A figure skater drawing in her arms spins faster on the same almost-frictionless turn.",
      ["a spinner slowing as its mass pulls inward", "a spinner's speed dropping when arms pull in", "spin speed that never changes under any motion"],
      "A satellite must reorient by changing its spin rate with no thrusters fired.",
      "command its masses to move inward, raising spin rate as momentum is conserved",
      ["fire the engines continuously to speed the spin", "deploy a parachute to slow the spin", "release the flywheel into space"]),
    c("centripetal acceleration", "the inward acceleration that keeps an object on a circular path",
      "A car rounding a flat curve needs the road's grip pulling toward the curve's center to hold its arc.",
      ["an outward fling that grows with slower speed", "an acceleration pointing along the car's heading", "a force that appears only when the road is banked"],
      "A highway curve must be designed so cars hold their arc without sliding outward.",
      "post a safe speed so required inward grip stays within the pavement's limits",
      ["raise the crest of the curve for lift", "paint the curve tighter for shorter paths", "post a higher minimum speed for grip"]),
    c("center of mass", "the balance point where an object's mass averages out",
      "A hammer tossed spinning follows a smooth arc traced by one special point inside it.",
      ["the heaviest single atom in the object", "the point where the object touches the ground", "the geometric middle regardless of mass spread"],
      "A stunt team must predict a thrown prop's smooth flight path while it tumbles.",
      "track the prop's center of mass, which arcs smoothly despite the tumble",
      ["follow the prop's brightest painted corner", "follow the end that spins fastest", "follow the prop's shadow only"])
  ],
  "PASCAL'S PRINCIPLES": [
    c("piston force ratio", "output force over input force equals the ratio of piston areas",
      "A wide piston with five times the small piston's area pushes back five times the input force.",
      ["output force equals input force regardless of piston sizes", "force grows with the smaller piston's area", "force falls as the wide piston's area grows"],
      "A press builder must promise a customer a tenfold force gain from a hand lever.",
      "size the wide piston at ten times the small piston's area",
      ["lengthen the pipes tenfold for a tenfold gain", "raise the fluid's temperature tenfold", "run the pump ten times faster at peak"]),
    c("distance trade-off", "the wide piston moves a shorter distance — travel is traded for force",
      "A lift's small piston sinks ten centimeters to raise the car just one.",
      ["the wide piston travels farther but weaker", "both pistons always move equal distances", "distance has no relation to piston size at all"],
      "An operator must explain why the lift pedal needs many strokes to raise the car.",
      "explain the trade: the small piston travels far so the wide one can lift hard",
      ["blame trapped air for the many strokes", "claim the pump is undersized for the job", "claim the car is lighter than it reads"]),
    c("hydrostatic pressure", "pressure at depth grows as weight of fluid above adds to surface pressure",
      "A dam's wall is thickest at the bottom because the water there presses hardest.",
      ["pressure that decreases with depth in a lake", "pressure that depends only on the lake's width", "pressure that stays constant at every depth"],
      "An aquarium's tallest viewing panel must survive the deepest filled section.",
      "rate the panel for pressure at the floor using depth, density, and surface pressure",
      ["rate the panel by the water's total weight alone", "rate the panel by the widest wall length", "rate the panel by surface pressure only"]),
    c("gauge pressure", "pressure measured relative to the surrounding air, not absolute zero",
      "A tire gauge reading 200 kilopascals means the air inside exceeds outside air by that much.",
      ["pressure counted from a perfect vacuum upward", "pressure that excludes atmospheric push entirely from tires", "pressure measured only inside sealed metal tanks"],
      "A maintenance sheet must state which pressure scale each tire figure uses.",
      "label the figures as gauge pressure, above local atmospheric pressure",
      ["label the figures as absolute from vacuum", "label them as weight per wheel", "label them as pipe flow rates"]),
    c("barometer", "an instrument where a mercury column's height balances the air's push",
      "When a storm nears, the mercury column in a barometer sinks as air pressure drops.",
      ["a device that spins as air pressure rises", "a gauge that measures only wind speed", "a tube that measures the mercury's own weight alone"],
      "A weather station must record true atmospheric pressure changes through a storm.",
      "read the mercury barometer's column height and log the pressure",
      ["count lightning flashes per minute", "record the anemometer's spins", "note the flag's direction each hour"]),
    c("U-tube manometer", "a liquid-filled U-tube that compares pressures by height difference",
      "A gas line's push is read directly from how far the liquid levels shift apart in the two arms.",
      ["a straight pipe that measures flow by bubbles", "a dial that counts gas volume passing", "a balance scale that weighs the gas itself"],
      "A lab bench needs a simple check that a gas supply line's push is steady.",
      "connect a U-tube manometer and read the steady height difference",
      ["time how long a balloon inflates", "weigh a deflating cylinder hourly", "listen to the line and estimate"]),
    c("Pascal's barrel experiment", "a tall thin water tube burst a strong barrel — pressure depends on height, not volume",
      "One extra story of narrow water column split a sealed barrel that a full tank could not.",
      ["a barrel that burst from the weight of a wide tank", "a barrel that resisted any height of water", "a barrel that burst only from boiling water"],
      "A safety class must show why tall thin fluid columns are dangerous.",
      "recreate the tall-tube barrel burst to show height, not volume, drives pressure",
      ["fill a wide tank beside the barrel and wait", "shake the barrel until the seams part", "heat the barrel until the water boils"]),
    c("pressure intensifier", "a two-stage piston setup that multiplies pressure beyond the supply line",
      "A shop line at 100 bar feeds an intensifier that delivers far higher pressure to a small tool.",
      ["a valve that vents pressure to protect the line", "a tank that stores pressure for later peaks", "a gauge that doubles its reading scale"],
      "A cutting station needs water pressure beyond the pump's own maximum.",
      "fit an intensifier stage driven by the existing line pressure",
      ["fit a larger return pipe to the reservoir", "replace the gauge with a wider scale", "add a second pump of the same rating in series"]),
    c("hydraulic accumulator", "a pressurized reservoir that stores fluid energy for peak demand",
      "When the press demands a sudden surge, the stored charge answers before the pump catches up.",
      ["a tank that cools the fluid between cycles", "a filter that cleans fluid before the pump", "a valve that blocks flow during surges"],
      "A stamping line's pump lags during sudden press strokes.",
      "install an accumulator charged between strokes to supply the surge",
      ["run the pump continuously at double speed", "widen the press cylinders for easier strokes", "pause five seconds before each stroke"]),
    c("relief valve", "a safety valve that vents fluid when pressure passes a set limit",
      "When a blocked line pushes past its setting, the valve cracks open and returns fluid to the tank.",
      ["a valve that raises pressure when it drops too low", "a valve that mixes air into the fluid supply", "a valve that seals tighter as pressure grows"],
      "A hydraulic circuit must never exceed its rated pressure even when a load jams.",
      "fit a relief valve set just above working pressure, venting back to tank",
      ["fit a stronger pump to force past jams", "thicken the hoses to hold any pressure", "add a warning light that triggers at burst"])
  ],
  "ARCHIMEDE'S PRINCIPLES": [
    c("specific gravity", "a material's density compared with water's, with no units",
      "A value of 0.8 means the material is four-fifths as dense as water and will ride on it.",
      ["a ratio that carries units of kilograms per liter", "a number that only applies to metals", "a measure of how quickly a liquid evaporates"],
      "A purchasing officer must check, from a data sheet alone, whether an oil floats on water.",
      "read the specific gravity — below 1.0 means it floats on water",
      ["read the flash point and compare with water", "read the price per liter and estimate", "read the viscosity and assume it sinks"]),
    c("hydrometer", "a floating calibrated stem whose depth reads a liquid's density",
      "The deeper the stem sinks, the lighter the liquid — the scale does the rest.",
      ["a device that spins to measure thickness", "a pump that draws samples for weighing", "a thermometer that reads density in celsius"],
      "A battery shop must test each cell's charge by its electrolyte's density.",
      "float a hydrometer in each sample and read the mark at the surface",
      ["time how long a drop takes to fall", "taste a drop and rate the sourness", "shine a light and rate the color"]),
    c("iron ship flotation", "a hull displaces enough water that the ship's average density stays below water's",
      "A steel ship floats because its hollow hull spreads the metal's weight across a huge volume of displaced water.",
      ["ships that float because iron becomes lighter when wet", "ships held up by their engines' thrust alone", "ships that float only when their cargo is light"],
      "A naval class must explain why a five-kilo steel sheet sinks but a folded steel bowl floats.",
      "fold it into a bowl so it displaces water weighing more than the steel",
      ["coat the sheet with wax to repel water", "heat the sheet until it softens and floats", "thin the sheet until it weighs nothing"]),
    c("fraction submerged", "the fraction below the surface equals the ratio of object density to fluid density",
      "An iceberg riding in seawater hides about nine-tenths of its bulk below the surface.",
      ["the submerged fraction depends on the object's color", "equal parts of any floater sit above and below", "floaters sit entirely above the surface line"],
      "A polar briefing must show crew how much of a drifting ice block lies underwater.",
      "compute the density ratio — that fraction sits below the waterline",
      ["estimate by counting visible layers of ice", "assume half sits below for every floater", "assume ice hides nothing below at all"]),
    c("buoyancy in air", "gases also buoy objects — helium rises when it displaces heavier air",
      "A helium balloon climbs because the air it pushes aside weighs more than the helium does.",
      ["balloons that rise because helium heats the air", "balloons lifted only by wind blowing under them", "balloons that rise because rubber is light"],
      "A festival crew must predict whether a sealed balloon will climb or sag.",
      "compare the balloon's total weight with the weight of the air it displaces",
      ["measure the balloon's paint and pattern", "time how fast the balloon's string swings", "weigh the balloon against a spare tire"]),
    c("neutral buoyancy", "weight balanced by buoyant force so an object hovers in the fluid",
      "A diver adjusts the vest until hovering takes no effort at any depth visited.",
      ["a state where the diver floats rapidly upward", "a state reached by removing all weights entirely", "a state where the diver rests on the bottom"],
      "An aquarium diver must hover motionless to film without stirring the sand.",
      "trim the vest inflation until weight and buoyant push balance exactly",
      ["drop all weights and grip the rail", "add lead until kneeling on the floor", "kick continuously to hold position"]),
    c("the crown test's method", "comparing water overflow of a crown and equal weight of pure gold exposed substitution",
      "Equal weights of gold and a gold-silver mix push aside different amounts of water.",
      ["a test that weighed the crown against gold bars on a balance", "a test that scratched the crown against glass", "a test that melted the crown at once"],
      "A docent must state exactly what the ancient crown test measured.",
      "compare overflow volumes for the crown and equal-weight pure gold",
      ["compare the crown's shine under torchlight", "compare the crown's ring when struck", "compare the crown's weight twice daily"]),
    c("load line", "the hull marking showing the deepest safe loading in a given water condition",
      "A ship riding at its line in fresh water may ride lower still in salty water without danger.",
      ["a line marking the engine's safe revolutions", "a painted line showing where cargo must sit on deck", "a line marking the hull's repair seams"],
      "A harbor inspector must confirm a loaded barge is legal for the season's water.",
      "read the load line mark against the waterline for the water's density and zone",
      ["count the cargo crates against the manifest", "measure the barge's length at the dock", "check the engine's exhaust color"])
  ],
  HISTORY: [
    c("Boyle's law", "Robert Boyle's 1662 finding that gas volume varies inversely with pressure",
      "Compressing trapped air to half its volume doubled its push back — Boyle published the relation in 1662.",
      ["a 1762 rule that volume grows with pressure", "Boyle's study of liquid metals in vacuum", "a 1662 catalog of air pumps by maker"],
      "A museum must state the first quantitative gas law and its year correctly.",
      "label it as Boyle's law, published in 1662, linking volume and pressure inversely",
      ["label it as Charles's 1787 climbing-volume rule", "label it as Torricelli's 1643 column height", "label it as Bernoulli's 1738 flow relation"]),
    c("Charles's law", "Jacques Charles's finding that gases expand equally for equal warming",
      "A balloon moved from a cold porch to a warm room swells as its gas warms at constant pressure.",
      ["a rule that gases shrink as they warm", "a rule that only liquids expand with heat", "a rule tying pressure to a gas's color"],
      "A display must pair a swelling balloon demo with the law it illustrates.",
      "present Charles's law: volume of a gas rises with its temperature at fixed pressure",
      ["present Boyle's law with a crushed bottle", "present Newton's cooling curve of tea", "present Torricelli's column with weather"]),
    c("Avogadro's hypothesis", "equal volumes of gas at the same conditions hold equal numbers of molecules",
      "One liter of oxygen and one liter of hydrogen at the same settings hold matching molecule counts.",
      ["a claim that heavier gases hold more molecules per liter", "a rule that molecules vanish at low pressure", "a count that only applies to noble gases"],
      "A chemistry corridor must explain why gas volumes add simply in reactions.",
      "credit Avogadro's hypothesis: equal volumes carry equal molecule numbers",
      ["credit Boyle's compressed-volume tables", "credit Perrin's microscope counts of grains", "credit Kelvin's absolute scale readings"]),
    c("the Kelvin scale", "Lord Kelvin's 1848 temperature scale anchored at absolute zero",
      "At zero kelvin, particle motion reaches its minimum — no colder reading exists.",
      ["a scale that starts at water's freezing point", "a scale whose degrees differ in size from celsius", "a scale measured in fahrenheit halves"],
      "A cryogenics lab must post temperatures on the scale that bottoms out at absolute zero.",
      "post all readings in kelvin, anchored at absolute zero",
      ["post readings in celsius above zero only", "post readings in fahrenheit fractions", "post readings in pascals per degree"]),
    c("Clausius and entropy", "Rudolf Clausius named entropy in 1865 and framed the second law",
      "Clausius showed that heat will not flow from cold to hot unaided, and gave entropy its name.",
      ["a 1920s radio engineer who named voltage", "a French balloonist who mapped cold air layers", "an Italian chemist who counted molecules"],
      "A thermodynamics hall must credit the naming of entropy and its era.",
      "credit Rudolf Clausius, who named entropy in 1865",
      ["credit Lord Kelvin's 1848 temperature essay", "credit Einstein's 1905 pollen paper", "credit du Châtelet's 1759 translation"]),
    c("Einstein's Brownian motion paper", "the 1905 explanation of jittering pollen as molecular bombardment",
      "Tiny grains in water jiggle because unseen molecules strike them unevenly, Einstein argued.",
      ["grains that jiggle because water currents swirl", "grains pushed by light pressure from the lamp", "grains magnetized by the microscope's lens"],
      "An exhibit must explain the jitter of smoke grains in air as evidence of molecules.",
      "present molecular bombardment as the cause, per Einstein's 1905 analysis",
      ["present the grains as tiny living swimmers", "present heat rising from the slide as the cause", "present static charge on the glass as the cause"]),
    c("Perrin's experiment", "Jean Perrin's 1908 counting of Brownian grains that fixed Avogadro's number",
      "By tallying grains at different heights, Perrin pinned down the number of molecules in a mole.",
      ["a count of atoms made by weighing one gold bar", "a survey of molecule speeds using color filters", "a tally of ions drawn to charged plates"],
      "A display must show how the reality of atoms was finally counted.",
      "feature Perrin's 1908 grain-counting that fixed Avogadro's number",
      ["feature Boyle's 1662 pressure tables", "feature Torricelli's 1643 mercury column", "feature Clausius's 1865 entropy papers"]),
    c("du Châtelet's Principia translation", "the 1759 French translation that spread Newton's mechanics across Europe",
      "Émilie du Châtelet's translated and annotated Newton opened continental physics to his system.",
      ["a Latin commentary that rejected Newton's laws", "a German pamphlet of telescope recipes", "an English almanac of comet dates"],
      "A history-of-science week must honor the work that carried Newton's book across Europe.",
      "feature du Châtelet's 1759 French Principia translation and commentary",
      ["feature a 1759 Paris tide calendar", "feature Voltaire's essay on English gardens", "feature a 1759 balloon design sketch"])
  ]
};

module.exports = { foundational, advanced };
