/*
 * TECH 1 concept library for the Geon GameHub questioner rebuild.
 * foundational = PREVIOUS questioner, advanced = NEW questioner.
 */
"use strict";

const c = (term, def, cue, misconceptions, setup, right, wrongs) =>
  ({ term, def, cue, misconceptions, setup, right, wrongs });

const foundational = {
  "SYSTEM UNIT AND ITS COMPONENTS": [
    c("power supply unit (PSU)", "the component that converts wall AC into the low DC voltages the parts need",
      "The wall socket gives alternating current, yet the motherboard's connector carries steady low-voltage direct current.",
      ["a component that boosts AC to power the monitor directly", "a storage device that keeps the operating system", "a chip that renders the display signal"],
      "A new build boots only when the wall cable is seated, so the inspector must name the unit that feeds the board.",
      "identify the PSU as the AC-to-DC converter feeding every component",
      ["call the CPU the unit that converts wall power", "call the hard drive the power converter", "call the GPU the AC adapter"]),
    c("central processing unit (CPU)", "the processor that executes instructions — the system's central calculator",
      "Every click becomes instructions that this chip fetches, decodes, and executes billions of times per second.",
      ["a chip that only stores files permanently", "a fan that cools the memory modules", "a card that outputs video to the screen"],
      "A trainee must point to the component that actually runs program instructions.",
      "identify the CPU under its cooler as the instruction-executing processor",
      ["point to the RAM sticks as the processor", "point to the optical drive as the processor", "point to the case fan as the processor"]),
    c("RAM", "fast working memory whose contents clear when power is cut",
      "The document you edit lives here while the PC is on, and vanishes if power is lost before saving.",
      ["memory that keeps files after shutdown", "storage measured in terabytes on platters", "a chip that permanently holds the BIOS"],
      "A lost report vanished when the power failed before saving — the class must name where it lived.",
      "explain it lived in RAM, which clears when power is cut",
      ["say it lived on the hard drive and is still there", "say the monitor erased it", "say the keyboard buffer deleted it"]),
    c("motherboard", "the main board that links every component together",
      "CPU, memory, storage, and ports all meet on this one large board bolted into the case.",
      ["a panel that only holds the power button", "a cable that plugs the monitor into the wall", "a tray that stores spare screws"],
      "A technician must name the single component that ties CPU, RAM, and drives into one system.",
      "identify the motherboard as the main interconnecting board",
      ["call the PSU the connecting board", "call the GPU the main board", "call the heat sink the main board"]),
    c("hard disk drive (HDD)", "a storage drive that records data magnetically on spinning platters",
      "Inside this drive, platters spin while an actuator arm reads and writes magnetic tracks.",
      ["a drive that stores data on flash chips only", "a drive with no moving parts at all", "a drive that only holds the boot logo"],
      "An old office PC produces faint clicking while saving files, and the trainee must name the likely drive type.",
      "identify the magnetic spinning-platter HDD as the likely drive",
      ["name the SSD, which has no moving parts", "name the PSU, which stores files", "name the case speaker as the drive"]),
    c("solid state drive (SSD)", "a storage drive built from flash memory with no moving parts",
      "Boots and file copies fly on this drive because no platter or arm must move.",
      ["a drive that records on spinning magnetic platters", "a drive that needs defragmenting weekly", "a drive that only works vertically"],
      "A workshop must pick the drive type that resists shock when laptops are moved while running.",
      "choose the SSD, whose flash storage has no moving parts",
      ["choose the HDD for its spinning platters", "choose the floppy drive for its sturdiness", "choose the optical drive for shock resistance"]),
    c("graphics processing unit (GPU)", "the chip that renders images and video for the display",
      "Games and video editing lean on this processor built for drawing millions of pixels at once.",
      ["the chip that manages network traffic", "the chip that stores the boot password", "the chip that converts AC to DC"],
      "A video editor's previews lag on the CPU alone, so the upgrade must target the right chip.",
      "upgrade the GPU, which handles image rendering",
      ["upgrade the PSU for rendering speed", "upgrade the case speaker for smoothness", "upgrade the CMOS battery for previews"]),
    c("chipset", "the board's traffic manager shuttling data between CPU, memory, and ports",
      "Every USB device and drive thread their data through this pair of controllers on the board.",
      ["the fan that cools the CPU socket", "the button that resets the clock", "the slot that holds the graphics card"],
      "A board diagram quiz asks which block routes data between the CPU and the USB ports.",
      "label the chipset as the data traffic manager",
      ["label the CMOS cell as the traffic manager", "label the ATX plug as the traffic manager", "label the I/O shield as the traffic manager"]),
    c("heat sink", "a metal block that pulls heat off a chip into the surrounding air",
      "Its fins spread the processor's heat so the fan's airflow can carry it away.",
      ["a device that heats the chip to working temperature", "a pump that drains liquid coolant out of the case", "a sensor that reports the chip's price"],
      "A CPU overheats because its metal fin block is clogged with dust.",
      "clean the heat sink fins so the airflow carries heat off the chip",
      ["remove the heat sink to let air touch the chip", "tape over the fins to smooth the airflow", "paint the fins to reflect the heat"]),
    c("SATA port", "the motherboard connector for a storage drive's data cable",
      "One thin L-shaped cable runs from this port to the back of the drive.",
      ["the socket where the monitor cable plugs", "the plug that carries wall power into the case", "the header for the case speaker"],
      "A new drive arrived with a thin L-notched cable that must find its home on the board.",
      "seat the SATA data cable into the SATA port",
      ["force it into the Ethernet port", "plug it into the PCIe slot latch", "attach it to the front-panel header"]),
    c("PCIe slot", "the expansion slot that accepts cards such as the graphics card",
      "The long latched slot near the CPU's bottom takes the display card with a firm click.",
      ["the socket that holds the CPU chip itself", "the port that accepts the keyboard cable", "the bay that mounts a disk drive"],
      "A graphics card must be fitted and latched so its bracket lines up with the case opening.",
      "press the card into the PCIe slot until the latch clicks",
      ["slide the card into a drive bay", "plug the card into the SATA port", "clip the card onto the RAM latch"]),
    c("case (chassis)", "the enclosure that holds, shields, and cools the computer's parts",
      "Every component mounts inside this steel box, behind its vented panels.",
      ["a bag that stores the cables when unused", "the screen that shows the boot logo", "the brick that converts wall power"],
      "A build table is ready with board, drives, and PSU, and the frame that unites them must be named.",
      "mount everything into the case, the enclosure for all parts",
      ["mount the parts on a cardboard sheet", "leave the parts on the anti-static mat", "hang the parts from the desk shelf"]),
    c("24-pin ATX connector", "the main power cable that feeds the motherboard",
      "The largest plug on the board's edge carries the main power from the supply.",
      ["the plug that powers only the speakers", "the cable that connects the two monitors", "the ribbon that links the drives"],
      "A dead board shows no lights although the PSU clicks once when the switch is pressed.",
      "check the 24-pin ATX plug is fully seated at the board's edge",
      ["check the headphone jack for power", "reseat the monitor cable first", "replace the keyboard before testing"]),
    c("front-panel header", "the pin block on the board where the case's buttons and LEDs connect",
      "The power button's thin wires land on this row of small pins near the board's bottom edge.",
      ["the slot where the graphics card latches", "the socket that holds the CPU", "the port that accepts the Ethernet cable"],
      "A finished build refuses to start when the power button is pressed, though the board's diagnostics light works.",
      "reseat the power button wires on the front-panel header",
      ["replace the CPU to fix the button", "reflash the monitor firmware", "swap the GPU for a newer card"]),
    c("optical drive", "a drive that reads and writes CDs or DVDs with a laser",
      "A disc tray slides out, accepts a shiny disc, and a laser reads the pits along its track.",
      ["a drive that stores data on magnetic tape reels", "a drive that reads flash memory cards", "a drive that buffers network video"],
      "A training lab must keep one drive that can read legacy installation discs.",
      "retain an optical drive for reading CD and DVD media",
      ["retain a floppy controller for DVDs", "retain a tape drive for discs", "retain a card reader for discs"])
  ],
  "OHS GUIDELINES AND DMA PROCEDURES": [
    c("ESD wrist strap", "a grounded strap that drains static from your body before you touch boards",
      "Rhea clips the strap to a grounded point before lifting the memory module from its bag.",
      ["a bracelet that powers the board during testing", "a watch that times each repair step", "a band that warms cold hands in the lab"],
      "An apprentice must touch a bare motherboard on a dry December morning.",
      "clip the wrist strap to ground first, then handle the board",
      ["rub the board on a wool sweater to equalize", "work barefoot on nylon carpet", "spray water directly on the board"]),
    c("antistatic mat", "a dissipative work surface where parts can rest safely",
      "The green mat under the build area is clipped to ground, so boards laid on it never collect charge.",
      ["a cushion that protects parts from bumps only", "a heat-proof sheet for soldering irons to rest on", "a sponge that holds cleaning alcohol"],
      "A technician must set a board down mid-repair without letting it gather static.",
      "lay the board on the grounded antistatic mat",
      ["lay it on the plastic desk protector", "hold it against a polyester sleeve", "rest it on a foam rubber pad"]),
    c("unplug before service", "disconnecting AC power before opening any equipment",
      "The cord leaves the wall before the side panel comes off — no exceptions, even for quick checks.",
      ["unplugging only after removing the parts", "leaving standby power on to speed testing", "working with one hand on the live cord"],
      "A service ticket asks for a drive swap in a desktop still humming at the reception desk.",
      "shut down, unplug the cord, and press the power button to drain before opening",
      ["open the panel while it hums and pull the drive", "flip the monitor off and proceed", "yank the SATA cable while running"]),
    c("proper lifting posture", "lifting with the legs and a straight back, load held close to the body",
      "The server box comes off the truck with bent knees and a flat back, not a rounded spine.",
      ["lifting with a rounded back for better grip", "holding the load at arm's length for balance", "twisting the spine while raising the box"],
      "A courier must move a 20-kilogram tower from a van to a second-floor desk alone.",
      "bend the knees, hold the tower close, and lift with the legs",
      ["bend at the waist and snatch it upward", "hold it far from the body to see the label", "pivot the torso while lifting to turn"]),
    c("cable management", "routing cords away from walkways to prevent trips and pulls",
      "Loose runs get strapped under the bench so feet and chair wheels never catch them.",
      ["wrapping cords in tape across doorways", "leaving slack loops where feet tangle", "running power cables across the aisle for speed"],
      "A new bench has a tangle of cords crossing the walkway behind the chairs.",
      "strap the runs under the bench and route them clear of walkways",
      ["tape the cords flat across the doorway", "gather the cords into a loose floor pile", "hang the cords at ankle height on hooks"]),
    c("PPE", "personal protective equipment such as gloves and eye protection",
      "Safety glasses go on before any cleaning solvent or cutting starts.",
      ["tools reserved only for managers' desks", "paperwork filed after each repair", "uniform badges worn at the entrance"],
      "A tech must scrub crusted dust from a case with a brush and solvent.",
      "wear safety glasses and gloves before brushing and solvent work",
      ["brush dust toward the face for visibility", "skip eye protection since dust feels soft", "wear sunglasses for style only"]),
    c("Class C electrical fire", "an energized-electrical fire fought only with non-conductive extinguishing agents",
      "A smoking PSU must never meet a water bucket — the fire is live electricity.",
      ["a fire class that water extinguishes safely", "a fire class that only paper fuels", "a fire class that burns without electricity"],
      "Smoke rises from a plugged-in power strip behind the bench.",
      "cut the power, then use the CO2 or dry-chemical extinguisher rated for electrical fires",
      ["throw water on the strip at once", "fan the smoke toward the alarm sensor", "cover the strip with a wool blanket"]),
    c("insulated tools", "hand tools rated to protect against live electrical contact",
      "The screwdrivers in the electrical kit wear rated sleeves along their shafts.",
      ["tools with rubber grips for comfort only", "tools coated in tape for repair work", "tools that conduct current freely"],
      "A tech must loosen a screw beside an exposed terminal that cannot be de-energized.",
      "use the rated insulated screwdriver for the job",
      ["grab any screwdriver from the drawer", "wrap a plain screwdriver with tissue", "use a wet steel file"]),
    c("handle boards by edges", "holding circuit boards by their edges to protect traces and parts",
      "Fingers stay on the board's rim, away from chips and printed lines.",
      ["gripping boards by their chips for a firm hold", "stacking boards face-to-face on the bench", "sliding boards across the table surface"],
      "An apprentice picks up a fresh motherboard bare-handed, palms flat on the surface.",
      "grip the board by its edges only, away from components",
      ["pin the board down by its heatsinks", "grab it by the RAM slots", "carry it balanced on one palm"]),
    c("workshop ventilation", "moving fresh air through the workspace to clear fumes and heat",
      "The solvent bench sits beside an exhaust fan so vapor never pools at breathing height.",
      ["sealing the room to keep dust from returning", "aiming fans from one bench to another", "closing vents to hold warmth in winter"],
      "A tech must clean several boards with solvent in a small closed stockroom.",
      "move to the ventilated bench or set an exhaust fan before starting",
      ["work behind the closed door for privacy", "hold your breath while scrubbing", "light a candle to mask the smell"])
  ],
  "ASSEMBLE AND DISASSEMBLE SYSTEM UNIT": [
    c("opening the side panel", "removing the panel screws and sliding the panel clear before working",
      "Two thumbscrews back off, the panel slides back, and the interior is exposed.",
      ["prying the panel with a flat bar while powered", "forcing the front bezel off sideways", "unscrewing the motherboard to open the case"],
      "A trainee faces a sealed tower that must be opened for its first inspection.",
      "loosen the rear thumbscrews and slide the side panel back",
      ["pry the top lid with a screwdriver tip", "pull the front face straight toward you", "flip the case and unscrew the bottom"]),
    c("grounding before touching parts", "touching bare metal or strapping in so body charge drains first",
      "One touch to the bare case frame equalizes the tech with the chassis before parts come out.",
      ["wearing gloves so static cannot pass", "holding the parts by their cables", "standing on carpet to absorb the charge"],
      "A builder steps across a carpeted floor toward an open case with memory in hand.",
      "touch the bare case metal first, then install the module",
      ["install the module quickly before charge builds", "wipe the module on the carpet", "hold the module by both chip rows"]),
    c("disconnecting power first", "unplugging the AC cord and draining residual charge before disassembly",
      "The cord leaves the socket, then the power button is pressed once to bleed the standby charge.",
      ["unplugging after the panel is off", "leaving the cord in for faster restarts", "cutting only the monitor's power"],
      "A disassembly job starts on a tower whose fan is still slowly spinning.",
      "unplug the cord, then press the power button to drain before unscrewing anything",
      ["catch the fan blade to stop it and continue", "switch off the power strip only", "pull the SATA cables while it spins"]),
    c("RAM latch release", "pushing the end clips outward to free a memory module",
      "Both end clips snap outward and the module springs up from its slot.",
      ["pressing the module down harder to unlock it", "pulling the module straight up with pliers", "twisting the module sideways until it loosens"],
      "An upgrade calls for removing an old memory stick from a latched slot.",
      "push both end latches outward and lift the module free",
      ["lever the module with a screwdriver shaft", "yank the module straight up by the heatsink", "bend the latches back with pliers"]),
    c("CPU socket lever", "lifting the retention arm before removing the processor",
      "The small arm swings out and up, releasing the plate that grips the chip.",
      ["unscrewing the CPU from its socket", "pulling the chip straight up by the heatsink", "twisting the chip until the pins snap"],
      "A CPU upgrade begins, and the old processor must come out intact.",
      "release the socket lever, open the plate, then lift the chip out",
      ["grip the chip with pliers and pull", "unscrew the four socket corners", "twist the chip a half turn and tug"]),
    c("thermal paste amount", "a rice-to-pea-sized dot that cooler pressure spreads evenly",
      "One small dot sits at the chip's center; mounting pressure does the spreading.",
      ["a full tube spread edge to edge", "four thick beads in the corners", "no paste at all for a dry fit"],
      "A cooler must be mounted on a freshly cleaned CPU.",
      "place one pea-sized dot of paste at the center, then mount the cooler",
      ["spread a thick layer over the whole board", "apply paste to the socket pins", "skip paste since the cooler is new"]),
    c("CPU alignment arrow", "matching the triangle on the chip to the socket's marked corner",
      "The gold triangle on the chip's edge lines up with the socket's marked pin-one corner.",
      ["inserting the chip in any orientation that fits", "rotating the chip until two pins enter holes", "clamping the chip down and trimming bent pins"],
      "A processor must enter its socket without a single bent pin.",
      "align the chip's triangle to the socket's marked corner, then seat it flat",
      ["press the chip in rotated to test the fit", "force the chip and file the socket ribs", "start one corner and snap the rest down"]),
    c("motherboard standoffs", "brass posts screwed into the case before the board is mounted",
      "The board rests on brass pillars so its solder points never touch bare steel.",
      ["mounting the board flat against the case wall", "mounting the board on foam tape", "mounting the board with wood screws only"],
      "A case arrives empty, and the new board must be mounted without shorts.",
      "screw in standoffs matching the board's holes, then seat the board on them",
      ["screw the board directly against the steel", "stick the board with double-sided foam", "float the board on spare cables"]),
    c("main power connections", "seating both the 24-pin board plug and the CPU power plug fully",
      "The wide plug clicks at the board's edge while the smaller square plug feeds the CPU corner.",
      ["connecting only the 24-pin and skipping the CPU plug", "connecting the CPU plug to the graphics card", "leaving both loose until the first boot test"],
      "A new build powers its fans briefly then dies on every start attempt.",
      "reseat both the 24-pin and the CPU power plugs until they click",
      ["replace the PSU with a higher wattage first", "reseat the RAM and ignore power plugs", "tape the loose plug in place"]),
    c("SATA cable notch", "the L-shaped key on a SATA connector that sets its orientation",
      "The L-shaped notch meets the matching tab so the cable enters one way only.",
      ["a round plug that spins to fit any way", "a cable that needs force to seat backwards", "a plug keyed by its cable color"],
      "A drive's data cable resists seating and the tabs are starting to bend.",
      "rotate the plug so its L-notch matches, then seat it gently",
      ["press harder in the current orientation", "trim the notch with a hobby knife", "switch to the power plug instead"]),
    c("front-panel LED polarity", "LED headers need plus and minus matched to the case wires",
      "The colored wire lands on the marked plus pin, or the LED stays dark.",
      ["LEDs that light regardless of orientation", "buttons that also need polarity matching", "headers that auto-detect the wire order"],
      "A finished build boots, but the power LED never lights.",
      "flip the LED header wires so plus meets the marked pin",
      ["replace the LED with a bigger lamp", "bridge both header pins with wire", "ignore it — LEDs fix themselves"]),
    c("PCIe seating latch", "pressing the card until the slot's latch clicks and the bracket screw seats",
      "Even pressure clicks the far latch while the bracket aligns with the case screw hole.",
      ["wiggling the card until it loosely fits", "screwing the bracket while the card sits half-out", "mounting the card on the case floor"],
      "A new display card shows a black screen and its fans twitch once at power-on.",
      "reseat the card fully until the slot latch clicks, then screw the bracket",
      ["reseat the RAM and call it fixed", "update the monitor's firmware", "bend the latch back with pliers"]),
    c("I/O shield placement", "fitting the board's rear shield into the case before mounting the board",
      "The snap-in shield seats into the rectangle before the board covers it.",
      ["mounting the board first and forcing the shield behind it", "leaving the shield off for better airflow", "gluing the shield over the ports after assembly"],
      "A board is laid in the case, but its rear ports catch on sharp bare edges.",
      "unsheathe the board, snap the I/O shield into the case, then remount the board",
      ["bend the ports flat to clear the opening", "cut the shield's tabs off with cutters", "tape foil over the raw opening"]),
    c("cable routing behind the tray", "running cables through the tray's grommets and strapping them flat",
      "Cables vanish through rubber grommets and reappear only where a plug is needed.",
      ["folding extra cable into the fan area", "leaving every cable loose across the board", "pinning cables under the GPU between fins"],
      "A build must leave clear airflow and safe clearance around the board.",
      "route cables through the tray grommets and strap them flat behind",
      ["bundle the slack on top of the heatsink", "weave cables between RAM sticks", "loop the slack around the CPU socket"]),
    c("pre-power checklist", "rechecking every plug and screw before the first power-on",
      "One final pass: power plugs seated, standoffs matched, no stray screws rattling.",
      ["powering on immediately to find loose parts by sound", "checking only the monitor cable", "skipping checks to save the customer's time"],
      "A first boot is moments away on a fresh build, with one screw left on the desk.",
      "run the checklist and account for every screw before pressing power",
      ["power on and shake the case to settle parts", "leave the screw inside near the PSU intake", "boot first, inspect after the beep"])
  ]
};

const advanced = {
  "SYSTEM UNIT AND ITS COMPONENTS": [
    c("VRM (voltage regulator module)", "the power stages beside the CPU socket stepping voltage down to safe levels",
      "Twelve-phase banks of small chokes and MOSFETs feed the processor a steady 1.2 volts from a 12-volt rail.",
      ["memory cells that store BIOS settings", "the sockets that hold system fans", "the ports that feed USB devices"],
      "An overclocked CPU crashes under load while its socket corner feels hot to the touch.",
      "inspect the VRM heat sinks — power stages are overheating under load",
      ["replace the RAM to fix the crashes", "reseat the front-panel header", "swap the SATA cables for shorter ones"]),
    c("CPU cache hierarchy", "tiny ultra-fast memory levels (L1, L2, L3) beside the cores",
      "The core checks L1 first, then L2, then the shared L3 before touching main memory.",
      ["a backup battery that powers the cores", "the queue of files waiting on the SSD", "the levels of the case's dust filters"],
      "A benchmark shows huge latency jumps whenever data leaves the chip itself.",
      "explain the miss pattern through the cache hierarchy — L1, L2, then L3",
      ["blame the HDD seek rate for the jumps", "blame the monitor's refresh lag", "blame the keyboard buffer for delays"]),
    c("dual-channel memory", "paired RAM sticks that widen the memory data path",
      "Two matched sticks in the right slots move data twice as wide as one alone.",
      ["two sticks that double the total storage size", "a setting that doubles the CPU's clock speed", "two memory sticks in series on one channel"],
      "A gaming rig with one 16 GB stick benches below an identical machine with two 8 GB sticks.",
      "fit matched sticks in the paired slots to enable dual-channel bandwidth",
      ["fit a single stick of twice the speed rating", "disable one stick to reduce errors", "set both sticks to half frequency"]),
    c("NVMe M.2 drive", "a bare flash drive on a small slot running at PCIe speed",
      "A gum-stick board screws flat onto the motherboard with no cables at all.",
      ["a drive that connects by SATA cable and power lead", "a memory module seated in the DIMM latches", "a card that mounts in a drive bay"],
      "A build must add fast storage with zero cables and minimal space.",
      "install the NVMe drive into the M.2 slot and fix its standoff screw",
      ["mount it in a 5.25-inch bay with adapters", "plug it into the front-panel header", "seat it in a DDR slot and latch it"]),
    c("northbridge and southbridge", "the legacy chipset split handling memory versus input/output traffic",
      "Older boards split duties: one chip fed the CPU and memory, the other handled ports and slots.",
      ["two fans that cool the CPU in stages", "two power connectors for redundant supplies", "two BIOS chips that mirror each other"],
      "A vintage board must be described accurately in a museum placard.",
      "label the two legacy chipset chips as the northbridge and southbridge",
      ["label them as dual VRM stages", "label them as twin BIOS banks", "label them as paired clock generators"]),
    c("ATX form factor", "the standard board size and mounting pattern shared by cases and boards",
      "A standard board's holes line up with a standard case's standoffs, whatever the brand.",
      ["a standard that fixes the CPU's brand choice", "a rule that all power supplies use one cable set", "a naming scheme for monitor sizes"],
      "A replacement board must fit an existing case without new holes.",
      "choose the matching ATX form factor for the case's standoff pattern",
      ["measure the case and drill fresh holes", "trim the board's edges to fit", "mount the board on an adapter plate of plexiglass"]),
    c("PSU capacitors", "internal components that smooth the supply's DC output ripple",
      "Inside the supply, capacitor banks flatten raw switched pulses into clean rails.",
      ["the coils that step up wall voltage directly", "the relays that switch the AC input", "the fans that cool the supply only"],
      "A system reboots under load while its rails show ripple waves on a scope.",
      "suspect aged output capacitors in the PSU and test the unit",
      ["replace the GPU to smooth the rails", "add RAM to stabilize the loads", "reseat the CPU cooler first"]),
    c("EPS 8-pin CPU power", "the dedicated 12-volt connector feeding the CPU socket",
      "The square-keyed 8-pin plug at the socket's corner is the CPU's own supply line.",
      ["the plug that powers the graphics card", "the cable that links two power supplies", "the header that runs the case fans"],
      "A board lights up but never POSTs, and its CPU power socket sits empty.",
      "seat the EPS 8-pin plug into the CPU power socket",
      ["plug a PCIe cable into the CPU socket", "move the 24-pin plug to cover both", "power the socket from a SATA lead"]),
    c("thermal paste", "the thin compound filling microscopic gaps between CPU and cooler",
      "Metal surfaces look flat but meet only at points — the paste fills the invisible valleys.",
      ["glue that bonds the cooler permanently", "a pad that insulates the chip from the cooler", "a lubricant that lets the cooler spin"],
      "A freshly built machine runs hot despite a correctly seated cooler.",
      "clean and reapply a thin paste layer to close the microscopic gaps",
      ["add a second cooler on top of the first", "remove the paste for direct metal contact", "apply paste around the socket instead"]),
    c("MOSFET", "the switching transistor that regulates power in the VRM stages",
      "These transistors chop the 12-volt rail thousands of times a second, and filters smooth the result.",
      ["diodes that store charges like tiny batteries", "relays that switch the wall power on and off", "sensors that log socket temperatures"],
      "A VRM's power stage reads shorted, and the board refuses to POST.",
      "test and replace the failed MOSFET in that power stage",
      ["replace the CMOS battery to clear the fault", "reflash the GPU BIOS instead", "swap the front-panel header pins"]),
    c("TPM header", "the connector for a trusted-platform security module",
      "A small add-on module seats on its header, giving the board a hardware key vault.",
      ["a port that adds extra fan speeds", "a slot that expands SATA lanes", "a header that boosts USB power"],
      "A security audit demands hardware key storage on an older board.",
      "fit the TPM module onto its dedicated header",
      ["plug the module into a USB port", "seat it in an M.2 slot", "attach it to the front-panel header"]),
    c("USB 3.0 header", "the 19-pin connector for fast front-panel USB ports",
      "The case's blue front ports trace back to this dense pinned block on the board.",
      ["the port cluster on the rear I/O plate", "the header for the case speaker", "the connector for the CPU fan"],
      "Front-panel ports work but negotiate old speeds on every device.",
      "move the case wire to the USB 3.0 header so front ports run fast",
      ["replace the mouse to fix the port speed", "flash the monitor firmware", "reroute the front audio cable"]),
    c("Molex connector", "the older 4-pin plug that powers fans and legacy drives",
      "The chunky white plug with four pins in a row feeds older fans and lamps.",
      ["the keyed plug for the CPU socket power", "the data cable for modern NVMe drives", "the ribbon for the front-panel buttons"],
      "A case fan with a white 4-pin plug must find power in a modern case.",
      "adapt the fan's Molex plug to a powered lead",
      ["plug the fan into the Ethernet port", "seat the fan plug into a DIMM slot", "cut the plug and twist wires to the PSU"]),
    c("case airflow path", "the planned front-to-back route that cool air takes through a case",
      "Air enters at the front, sweeps the components, and exits at the rear and top.",
      ["a loop that recycles hot air at the GPU", "a path that pulls air in through the rear exhaust", "a route that enters at the top and pools at the base"],
      "A build runs cool on the bench but heats up mounted in the case.",
      "set fan directions front-in and rear-out to restore the designed airflow path",
      ["flip the rear fan to blow inward", "seal all vents and rely on the PSU fan", "point the top fans at the motherboard"]),
    c("motherboard standoff map", "matching brass post positions to the board's screw holes",
      "Extra standoffs behind unused holes touch solder points and short the board to ground.",
      ["posts placed anywhere that fits the screwdriver", "standoffs needed only under the CPU socket", "posts optional when the board is screwed tight"],
      "A new build dead-shorts: fans twitch once and nothing more, with one standoff loose in the box.",
      "remove the unmatched standoff so it no longer bridges the board's rear",
      ["tighten every screw past snug", "add another standoff under the GPU", "insulate the case with plastic sheets"])
  ],
  "OHS GUIDELINES AND DMA PROCEDURES": [
    c("ESD protected area (EPA)", "a controlled zone with grounded benches, flooring, and wrist points",
      "Inside the taped floor lines, every surface and strap ties to one common ground point.",
      ["a clean room where only managers may enter", "a storage area for sealed spare parts", "a zone where static charges build freely"],
      "A repair center must set up a proper zone for board-level work.",
      "mark and equip an EPA with grounded bench, floor, and wrist points",
      ["tape a clean zone on the carpet and work inside", "ban wrist straps inside the zone", "share one ground wire across three rooms"]),
    c("humidity and ESD risk", "dry air raises static risk while moderate humidity lowers it",
      "On dry December days, walks across carpet build charges that moderate-humidity days bleed away.",
      ["static risk that vanishes in air-conditioned rooms", "humidity that always increases static build-up", "weather with no effect on static at all"],
      "Static failures spike at the bench every dry season.",
      "raise relative humidity toward the 40 to 60 percent band and re-verify grounding",
      ["raise the air-con cooling to dry the room further", "double the wrist strap resistance", "move the benches onto rubber mats"]),
    c("lockout-tagout", "isolating and tagging a machine's power so it cannot be re-energized mid-service",
      "The breaker locks off, a signed tag hangs on it, and only the tag's owner clears it.",
      ["taping the power button so nobody presses it", "logging out of the machine's software account", "tying the door shut while work proceeds"],
      "A technician reaches into a conveyor's drive cabinet during maintenance.",
      "apply lockout-tagout on the drive's breaker before touching the cabinet",
      ["shout clearly before each adjustment", "hold the door interlock closed by hand", "wear one rubber glove and proceed"]),
    c("RSI prevention", "micro-breaks and neutral wrist posture that avoid repetitive strain injury",
      "Every half hour, hands drop from the keyboard and wrists straighten before resuming.",
      ["typing harder to build wrist strength", "resting wrists on the desk's sharp edge", "skipping breaks to finish the queue faster"],
      "A data-encoder reports tingling wrists after full-day shifts.",
      "schedule micro-breaks and reset the station for neutral wrist angle",
      ["add wrist braces and lengthen shifts", "switch to a harder keyboard for training", "swap the worker to mouse-only duty"]),
    c("isopropyl alcohol safety", "handling flammable solvent with lids closed, ventilation, and no flames",
      "The bottle recaps between wipes, and the soldering iron stays across the room.",
      ["solvent that burns out only at torch heat", "a cleaner safe beside lit cigarette lighters", "a fluid that stores fine in open cups"],
      "A bench job calls for solvent cleaning near a hot-work station.",
      "move cleaning to the ventilated bench and recap the solvent before any hot work",
      ["clean beside the iron to save steps", "pour solvent into an open dish for the day", "use a torch lighter to speed drying"]),
    c("capacitor discharge", "draining stored charge from large capacitors and verifying before touching circuits",
      "The bleeder tool drains the big caps, then the meter confirms zero volts.",
      ["capacitors that self-discharge within one second", "caps that hold charge only while plugged in", "discharge that happens by unscrewing the board"],
      "A technician opens a switched-mode supply that has been unplugged for a minute.",
      "discharge the bulk capacitors with a bleeder and verify zero with the meter",
      ["unscrew the board and pull by the cap cans", "shake the board to loosen the charge", "short every cap with a wet screwdriver"]),
    c("incident reporting", "logging every accident and near-miss so causes get fixed",
      "Even the dropped screwdriver that missed a foot gets a line in the log that afternoon.",
      ["reports reserved for injuries needing clinics", "verbal mentions that skip the record", "annual summaries without dated entries"],
      "A shelf bracket fails and drops a monitor beside a worker — no injury results.",
      "file the near-miss report the same day so the bracket design gets reviewed",
      ["say nothing since nobody was hurt", "mention it at the year-end meeting only", "fix the bracket quietly and delete the photos"]),
    c("5S housekeeping", "sort, set in order, shine, standardize, sustain — an orderly, safe workspace",
      "Shadow boards show missing tools at a glance, and aisles stay clear by habit.",
      ["a cleaning rota that runs once a year", "a policy of hiding tools to prevent theft", "a system of stacking parts highest first"],
      "A service bay's walkways fill with parts and cords within a week of each rush job.",
      "run the 5S cycle: clear, arrange, clean, standardize, and audit weekly",
      ["close the bay for a month-long deep clean", "store overflow parts in the walkway", "ban all labeling to save on tape"]),
    c("safety eyewear", "impact-rated glasses worn for solvents, brushing, and cutting",
      "Rated glasses go on before the first blast of compressed air or splash of solvent.",
      ["eyeglasses that satisfy the rating by default", "glasses needed only when a supervisor watches", "face shields reserved for welding alone"],
      "A tech must blow dust from heatsinks and scrub corrosion with solvent.",
      "wear rated safety glasses for both the air blast and the solvent work",
      ["squint and aim away from the face", "wear ordinary fashion sunglasses", "hold the work at arm's length instead"]),
    c("emergency preparedness", "knowing exits, cut-offs, and first-aid points before work begins",
      "The new hire walks the exits and breaker map on day one, before touching a bench.",
      ["learning exits after the first alarm sounds", "relying on supervisors to direct every event", "keeping emergency gear locked for safety"],
      "A new technician joins a workshop full of energized rigs.",
      "walk the exits, main cut-off, and first-aid kit locations before starting",
      ["start bench work and ask during a fire", "memorize the exits only after orientation week", "leave preparedness to the security guard"])
  ],
  "ASSEMBLE AND DISASSEMBLE SYSTEM UNIT": [
    c("stray standoff short", "an unmatched brass post behind the board shorting traces and blocking power-on",
      "Fans twitch once and die on power-up; inspection finds one post under an unused hole.",
      ["a post that only causes cosmetic scratches", "standoffs that improve grounding anywhere they sit", "a fault that appears only in software"],
      "A fresh build dead-shorts with fans twitching once at the power switch.",
      "back out the unmatched standoff and re-run the power-on test",
      ["swap the PSU for double the wattage", "reseat all RAM sticks in new slots", "flash the BIOS to clear the short"]),
    c("LGA socket pin care", "never dropping the CPU or touching the delicate socket contact pins",
      "The chip lowers flat into the frame — one graze across the pins can kill the board.",
      ["pins that bend back into place under load", "a socket that tolerates angled insertions", "pins that survive contact with screwdrivers"],
      "A CPU upgrade looms over an open socket on a customer's board.",
      "lower the chip flat into the aligned frame without touching the pins",
      ["test-fit the chip at a slight angle first", "brush the pins lightly to align them", "rest the chip on the socket edge while aligning"]),
    c("cooler cross-tightening", "tightening cooler screws in an X pattern a few turns at a time",
      "Opposite corners tighten in sequence so the paste spreads evenly under even pressure.",
      ["running one screw fully down before the rest", "tightening corners clockwise in a circle", "hand-tightening two corners only"],
      "A mounted cooler shows paste squeezed out one side and bare metal on the other.",
      "unmount, clean, remount, and tighten in the X pattern by small steps",
      ["retighten the loose corner only", "add paste on the bare side and remount", "swap to a bigger cooler to cover gaps"]),
    c("EPS versus PCIe plugs", "CPU and graphics power plugs look close but are keyed differently — never force",
      "The 4+4 square-keyed block feeds the CPU; the 6+2 with one clipped pin feeds the card.",
      ["plugs that interchange freely between slots", "keying that matters only on cheap supplies", "connectors that mate under firm pressure"],
      "A builder forces a plug that fits only after cutting a key, then the board never POSTs.",
      "match each plug to its keyed socket — EPS to board, PCIe to card",
      ["trim conflicting keys to make plugs fit", "swap the two plugs to test polarity", "splice both plugs into one lead"]),
    c("M.2 mounting", "seating the drive at an angle, latching it, then fixing the standoff screw",
      "The gum-stick drive tilts in, clicks into the latch, and one small screw anchors the far end.",
      ["drives that screw flat at both ends first", "M.2 drives that connect by cable", "drives that press into place like RAM"],
      "A new NVMe drive must be fitted to a bare slot.",
      "angle the drive in, latch it, then secure the standoff screw at the far end",
      ["force the drive flat and press until it clicks", "screw both ends before seating contacts", "tape the drive over the slot"]),
    c("front-panel pinout chart", "following the board manual's diagram for the case's button and LED wires",
      "Case labels vary, so the manual's pin map settles where each wire lands.",
      ["wires that sort themselves on any pins", "color codes that are universal across cases", "a chart needed only for audio leads"],
      "A build's power button works but the reset button restarts nothing.",
      "check the manual's pinout and reseat the reset wires on their pair",
      ["swap the power and reset wires wholesale", "bridge the reset pins with a screwdriver", "disable the reset button in software"]),
    c("memory training delay", "long first-boot pauses while the platform trains new memory",
      "The first power-on sits dark for a minute while speeds negotiate, then the screen lights.",
      ["a sign that RAM seats were miswired", "a delay caused only by slow drives", "a hang that means the CPU has failed"],
      "A newly built machine's first start shows a black screen for over a minute.",
      "wait through the memory-training pause before assuming a fault",
      ["cut power at 30 seconds to retry", "reseat the CPU to wake the memory", "flash the GPU BIOS mid-training"]),
    c("GPU sag support", "a bracket or prop that keeps heavy cards from stressing their slot",
      "A support post under the card's far end keeps the slot from bearing its weight.",
      ["a strap that ties the card to the PSU", "a tilt that slots cards fit automatically", "a second slot that carries half the weight"],
      "A heavy card's near end droops visibly after months of use.",
      "fit an anti-sag support under the card's far end",
      ["reseat the card higher in the slot", "tie the card's cable taut to the case", "remove the bracket to reduce weight"]),
    c("modular PSU cable matching", "modular cables are not interchangeable between supply brands or models",
      "Pin orders differ, so one brand's modular lead can feed 12 volts where another expects ground.",
      ["cables that follow one universal pin standard", "swaps that are safe between same-color units", "mixing that only harms low-wattage units"],
      "A spare modular cable from an old unit slots neatly into a new supply.",
      "use only the cables shipped with that exact PSU model",
      ["test the spare cable at low load first", "match cables by connector color", "reuse cables if the gauge looks equal"]),
    c("fan direction pairing", "front fans blowing in, rear fans blowing out, matching the case design",
      "Arrows on the fan frame show blade spin and airflow — the front pushes in, the rear pulls out.",
      ["all fans blowing outward for maximum extraction", "all fans blowing inward to pressurize dust out", "direction that matters only for lighting effects"],
      "A build's rear exhaust spins the wrong way, pushing air against the flow.",
      "flip the rear fan so airflow runs front-to-back",
      ["reverse the front fans to match the rear", "remove the rear fan entirely", "add a top fan blowing inward"]),
    c("snug motherboard screws", "board screws need firm contact, not maximum torque",
      "Each screw turns until it meets the standoff, then a gentle pinch — no more.",
      ["screws that need full driver force to hold", "screws that loosen under light torque", "a torque that differs per screw color"],
      "A board's corner cracks around its mount after a heavy-handed build.",
      "re-seat all screws to snug contact and inspect the cracked area",
      ["replace the board with a steel-backed one", "skip the cracked corner's screw forever", "tighten the remaining screws harder"]),
    c("pre-disassembly photos", "photographing wiring and mounts before tearing a machine down",
      "Clear shots of every header and plug make the reassembly sequence certain.",
      ["photos that replace the service manual entirely", "pictures needed only for warranty claims", "shots of the serial plate as proof of work"],
      "A volunteer must strip a donated rig with unfamiliar wiring for refurbishing.",
      "photograph all connections and mounts before disconnecting anything",
      ["shoot only the case exterior for records", "film the boot screen as reference", "snap the desk setup and begin"]),
    c("drive rail release", "slide-lock bays free drives only after the rail latch is pressed",
      "The latch clicks, the rail slides back, and the drive leaves the cage cleanly.",
      ["rails that release by yanking the cables", "bays that open by prying the cage lips", "drives that unscrew from the front bezel"],
      "A drive refuses to budge from its tool-less cage during a swap.",
      "press the rail's release latch, then slide the drive out",
      ["lever the drive with a flat bar", "pull the SATA plugs to drag it free", "unscrew the whole cage from the case"]),
    c("header detachment before board removal", "unclipping front-panel and fan wires before lifting the board out",
      "Every small plug leaves its header first, so the board lifts free with no taut wires.",
      ["lifting the board with wires attached for speed", "cutting zip ties to free the board faster", "removing the PSU to release tension instead"],
      "A board must come out for a socket inspection but resists at its bottom edge.",
      "unclip all front-panel and fan plugs, then lift the board clear",
      ["pull harder against the wire tension", "bend the board to slip past the wires", "unsolder the stubborn header block"]),
    c("PSU voltage switch", "the 115/230V selector that must match the local wall supply before power-on",
      "An imported build trips the breaker the instant it is plugged in — the red switch on the supply is set for another country.",
      ["a switch that selects the PSU's fan speed", "a selector that changes the output wattage rating", "a switch that matters only for dual-GPU rigs"],
      "A donated tower built abroad must run safely on a 230-volt wall supply.",
      "verify the supply's selector reads 230 before the first power-on",
      ["cover the switch with tape and plug in anyway", "flip it to 115 to test both settings", "swap the wall socket instead of the setting"])
  ]
};

module.exports = { foundational, advanced };
