/*
 * TECH 2 concept library for the Geon GameHub questioner rebuild.
 * foundational = PREVIOUS questioner, advanced = NEW questioner.
 */
"use strict";

const c = (term, def, cue, misconceptions, setup, right, wrongs) =>
  ({ term, def, cue, misconceptions, setup, right, wrongs });

const foundational = {
  "BIOS, CMOS, UEFI": [
    c("BIOS", "the basic firmware that wakes the hardware and hands control to the bootloader",
      "Long before any logo or Windows screen, one embedded program wakes the memory and disks.",
      ["the operating system's disk manager", "a driver that runs after Windows loads", "a tool that only checks the battery"],
      "A trainee must name the very first code that runs when a desktop powers on.",
      "identify the BIOS as the first firmware that initializes hardware",
      ["call Windows the first code to run", "call the graphics driver the first code", "call the antivirus the first code"]),
    c("POST", "the power-on self test that checks core hardware before booting",
      "One short beep means memory, video, and keyboard passed their quick checks.",
      ["a scan that runs inside Windows nightly", "a test that checks only the internet link", "a screen that lists file errors on the disk"],
      "A machine halts before any logo with three long beeps and no display.",
      "read the POST beep pattern — it flags failing core hardware",
      ["run a disk scan from within the OS", "replace the speakers to silence the codes", "ignore it — POST never reports faults"]),
    c("beep codes", "audio signals that flag failing memory or video before the screen works",
      "Three short beeps repeat while the screen stays dark — the pattern points at memory.",
      ["tones that announce Windows updates", "melodies played by the sound card driver", "signals that only report keyboard errors"],
      "A service call reports repeated beeps and a black screen at power-on.",
      "count the beeps and match the pattern to the board's beep-code table",
      ["replace the case speaker to stop the beeps", "mute the audio in the OS settings", "assume the monitor cable is loose"]),
    c("CMOS memory", "the small store that keeps BIOS settings between boots",
      "Boot order, time, and fan curves survive shutdown because this little store holds them.",
      ["a backup of all user files", "the memory that runs open applications", "a cache for the web browser"],
      "A PC forgets its boot order and clock at every unplugging.",
      "suspect the CMOS store and its battery, then retest after replacing the cell",
      ["reinstall Windows to fix the settings", "replace the hard drive to hold settings", "disable the clock to stop the resets"]),
    c("CMOS battery", "the coin cell that keeps settings and the clock alive with power off",
      "A CR2032 coin on the board feeds the settings store and clock while unplugged.",
      ["a cell that powers the fans at standby", "a backup for the graphics card's memory", "a cell that boots the PC without AC"],
      "A machine reports the wrong date at every cold start.",
      "replace the coin cell on the board and reset the date once",
      ["re-paste the CPU to fix the clock", "update the audio driver for the date", "swap the PSU to hold the time"]),
    c("BIOS setup key", "the key such as Delete or F2 pressed at POST to open firmware settings",
      "Tapping Delete as the machine starts opens the firmware's own screens.",
      ["a key pressed inside Windows to change firmware", "a combo typed at the login screen", "a switch on the PSU to open settings"],
      "A technician must change the boot order before any operating system loads.",
      "tap the setup key during POST to open the firmware settings",
      ["open Device Manager inside Windows", "boot a repair disc and edit settings there", "hold the power button to enter setup"]),
    c("boot order", "the priority list of devices the firmware tries to boot from",
      "USB first means an inserted installer starts before the internal drive.",
      ["the list of programs that start inside Windows", "the order of users at the login screen", "the sequence of fans spinning up"],
      "A repair USB must start before the machine's own Windows copy.",
      "set USB first in the firmware's boot order, then restart",
      ["copy the USB files onto the desktop", "rename the USB drive to C:", "unplug the internal drive permanently"]),
    c("BIOS update (flashing)", "carefully replacing firmware to fix bugs or add CPU support",
      "A stable power supply and the exact model file matter, or the board may not start again.",
      ["a routine cleanup that runs weekly", "an update installed through Windows Update", "a refresh that overwrites user files"],
      "A new-generation CPU needs a board firmware newer than the one installed.",
      "flash the exact-model firmware from USB, on stable power, once",
      ["flash any same-brand firmware to be safe", "flash repeatedly during a storm for luck", "update the firmware from within a game"]),
    c("legacy BIOS limits", "old BIOS boots required MBR disks, capping drives near 2 TB",
      "A 4 TB drive on an old BIOS shows only the first slice as bootable.",
      ["a limit that applies only to USB drives", "a cap fixed by the case's physical size", "a limit set by the monitor's resolution"],
      "A 4 TB boot disk refuses to boot on a 2010-era machine.",
      "explain the legacy BIOS MBR limit that caps bootable space near 2 TB",
      ["blame the SATA cable for the missing space", "blame the operating system's license", "blame the power supply's rating"]),
    c("UEFI", "modern firmware with graphical setup, GPT boot, and built-in tools",
      "New boards boot from mouse-clickable screens and handle huge drives natively.",
      ["a Windows utility for disk cleanup", "a driver suite for gaming mice", "a recovery partition on the hard drive"],
      "A modern board must boot a 6 TB disk with a graphical setup screen.",
      "confirm the board runs UEFI, which supports GPT boot and graphical setup",
      ["upgrade the monitor to enable UEFI", "install more RAM to unlock UEFI", "disable the disk cache to get UEFI"]),
    c("GPT partition table", "the GUID partition table supporting huge disks and many partitions",
      "GPT charts a 6 TB drive into as many partitions as the system allows, with no 2 TB wall.",
      ["a table that only works on floppy disks", "a scheme limited to four primary partitions", "a layout that requires legacy BIOS"],
      "A technician must partition an 8 TB data disk without the old four-partition cap.",
      "initialize the disk as GPT to unlock its full size and partition count",
      ["initialize as MBR and accept the caps", "format as FAT32 to raise the cap", "split the disk into two 4 TB drives"]),
    c("Secure Boot", "the UEFI feature that checks bootloaders against trusted keys before running them",
      "Unsigned boot code stops at the door because the firmware verifies its signature first.",
      ["a lock that stops Windows from updating", "a password gate for the BIOS setup screen", "a firewall for internet traffic"],
      "A security audit wants proof that unsigned boot code cannot start.",
      "enable Secure Boot so only signed bootloaders run",
      ["set a BIOS password to block boot code", "disable the network in firmware", "install an antivirus on a USB stick"]),
    c("fast boot", "a firmware option that skips some checks to shorten startup",
      "POST shortens as the firmware skips full device sweeps on each start.",
      ["a mode that overclocks the CPU at boot", "a setting that loads Windows files to RAM", "a feature that skips the login screen"],
      "A workshop machine must reach the operating system as quickly as possible each morning.",
      "enable fast boot so POST skips lengthy checks",
      ["remove the case fan to shorten POST", "unplug all USB devices permanently", "disable the clock to save startup time"]),
    c("BIOS password", "a firmware-level lock on entering setup or powering on",
      "Without the password, the firmware blocks setup changes even before any OS appears.",
      ["the Windows login password", "the Wi-Fi password stored in firmware", "the password for the BIOS update file"],
      "A lab machine must refuse boot-settings changes by students.",
      "set a firmware admin password so setup stays locked",
      ["set the Windows screensaver password", "hide the setup key's label on the case", "unplug the keyboard during startup"]),
    c("load optimized defaults", "resetting firmware settings to the board's tested baseline",
      "One menu item restores factory-tuned settings after a bad overclock.",
      ["a tool that formats the boot drive", "an option that copies Windows settings", "a command that updates all drivers"],
      "A failed overclock leaves a machine that beeps and will not display.",
      "clear CMOS, then load optimized defaults in firmware setup",
      ["reinstall Windows to clear the overclock", "replace the GPU to restore display", "lower the monitor's refresh rate"])
  ],
  NETWORKING: [
    c("IP address", "the logical number that identifies a device on an IP network",
      "Every device on the office LAN carries one, written as four dot-separated numbers.",
      ["the serial number printed on the device case", "the name of the network's administrator", "the cable's color code standard"],
      "Support asks a user for their machine's network identity number on the LAN.",
      "read the IPv4 address from the network settings, like 192.168.1.24",
      ["read the monitor's model number", "read the Windows license key", "read the router's brand name"]),
    c("router", "the device that forwards traffic between different networks",
      "Home traffic reaches the internet because this box chooses paths between the two networks.",
      ["a device that only repeats Wi-Fi signals", "a switch that links devices in one LAN", "a modem that converts coax only"],
      "A small office must let its LAN reach the internet through one gateway box.",
      "install a router as the gateway between LAN and internet",
      ["stack two switches and label one a router", "add a hub to the internet line", "assign static names to every PC"]),
    c("network switch", "the device that connects many devices within one LAN by MAC address",
      "Each desk cable lands on this box, which sends frames only to the right port.",
      ["a device that assigns internet IP addresses", "a box that routes between networks", "an antenna that spreads Wi-Fi"],
      "Twelve office PCs must share one LAN without traffic flooding every port.",
      "connect the PCs through a switch that forwards by MAC address",
      ["connect all PCs through one shared hub", "give each PC its own router", "daisy-chain PCs by firewire"]),
    c("DHCP", "the service that hands out IP settings to devices automatically",
      "A new laptop joins and receives address, mask, gateway, and DNS without any typing.",
      ["a protocol that speeds up the Wi-Fi radio", "a service that blocks unknown devices", "a tool that scans for open ports"],
      "A visitor's laptop must join the LAN without manual address entry.",
      "let the DHCP server lease the laptop its settings automatically",
      ["type a fixed public address into the laptop", "disable the laptop's firewall to connect", "assign the printer's address to the laptop"]),
    c("DNS", "the service that translates names like example.com into IP addresses",
      "Typing a site name works because this service looks up its number behind the scenes.",
      ["a service that stores website files", "a protocol that compresses web pages", "a server that hosts email only"],
      "Browsing by number works, but browsing by name fails on one PC.",
      "fix the DNS server entries in that PC's network settings",
      ["replace the network cable first", "reinstall the browser from scratch", "change the PC's IP address at random"]),
    c("default gateway", "the router address a device uses to reach any other network",
      "Traffic to the internet leaves through this one local address set on each PC.",
      ["the first computer ever installed on a LAN", "the address of the nearest printer", "the switch's management port number"],
      "A PC reaches local shares but never any internet site.",
      "set the correct default gateway address on the PC",
      ["add a second switch between PC and wall", "remove the subnet mask to widen the LAN", "disable the firewall to open routing"]),
    c("subnet mask", "the setting that splits an address into network and host portions",
      "With 255.255.255.0, the first three numbers name the network and the last names the device.",
      ["a mask that hides the screen's content", "a password for the wireless network", "a filter that blocks web categories"],
      "Two PCs with correct addresses still cannot see each other on the LAN.",
      "check both PCs share the matching subnet mask",
      ["swap both PCs' cables for longer ones", "set both PCs to public network profile", "rename both PCs to match"]),
    c("RJ45 connector", "the 8-wire plug on the end of an Ethernet cable",
      "The clear plug clicks into the NIC's port with eight small contacts in a row.",
      ["the barrel plug for power adapters", "the threaded connector for coax cable", "the USB plug on a wireless dongle"],
      "A technician must terminate a fresh Ethernet run for a wall socket.",
      "crimp an RJ45 plug onto the cable in the wiring order",
      ["fit an RJ11 phone plug to the Ethernet run", "solder the cable directly to the port", "twist the eight wires and tape them"]),
    c("SSID", "the broadcast name that identifies a Wi-Fi network",
      "Phones list the office network by this human-readable name.",
      ["the Wi-Fi network's password", "the router's model number", "the wireless channel's frequency"],
      "Guests cannot find the visitor Wi-Fi among six neighboring networks.",
      "announce a distinct SSID for the guest network",
      ["set the guest network to hidden mode", "change the router's admin password", "move the router to the ceiling"]),
    c("MAC address", "the factory-burned hardware address of a network adapter",
      "Every adapter ships with this fixed 12-hex-digit identifier.",
      ["the Apple computer's address on a LAN", "the address stored in the router's memory", "the mailbox number of the building"],
      "An access control list must admit two specific laptops by hardware identity.",
      "register each laptop's adapter MAC address on the list",
      ["register each laptop's IP address permanently", "register the users' account names", "register the laptops' serial plates"])
  ],
  "WINDOWS INSTALLATION": [
    c("clean installation", "wiping the target drive and installing Windows fresh",
      "The old system, files, and programs all go, and a brand-new system starts from zero.",
      ["an install that keeps all files and programs", "an update applied inside running Windows", "a repair that only fixes system files"],
      "A resale PC must leave with no trace of the previous owner's data.",
      "perform a clean installation that wipes the drive first",
      ["delete the desktop icons before sale", "run disk cleanup inside the old Windows", "hide the old user accounts from login"]),
    c("upgrade installation", "installing a new Windows version over the existing one, keeping files and apps",
      "The setup runs from inside Windows, and afterwards the desktop, files, and programs remain.",
      ["an install that formats the system drive first", "an install that only copies drivers", "an install that doubles the disk size"],
      "An office must move to a newer Windows without losing installed applications.",
      "run the upgrade installation from within the current Windows",
      ["wipe the drive and rebuild every machine", "copy the Windows folder onto a USB", "install to a second disk and switch cables"]),
    c("bootable USB installer", "a USB stick prepared to start Windows setup by itself",
      "The Media Creation Tool writes the installer so the PC can start from the stick.",
      ["a USB drive that stores the install log only", "a stick that carries the license key", "a drive that backs up the old Windows"],
      "A laptop's drive is blank and has no optical drive at all.",
      "create a bootable USB installer and start the laptop from it",
      ["copy the setup folder onto the blank drive", "boot from a phone tethered by cable", "install through the recovery partition email"]),
    c("product key", "the license code that activates Windows",
      "The 25-character code proves the license during or after setup.",
      ["the Wi-Fi password typed during setup", "the admin account's password", "the USB stick's serial number"],
      "Setup asks for proof of licensing before the edition can install.",
      "enter the 25-character product key when prompted",
      ["type the monitor's serial number", "enter the Microsoft account password", "skip and copy a neighbor's install ID"]),
    c("partitioning during setup", "dividing the drive into sections before Windows installs",
      "Setup's drive screen lets one disk become system and data sections.",
      ["splitting the monitor into two screens", "dividing RAM between two systems", "sorting files into colored folders"],
      "One physical drive must hold the system and a separate data area.",
      "create two partitions during setup: one for Windows, one for data",
      ["install twice on the same partition", "buy a second drive and mirror it", "compress the Windows folder in half"]),
    c("NTFS", "the modern Windows file system with permissions and journaling",
      "File permissions and crash-safe metadata come with this Windows-native system.",
      ["a compression tool for old drives", "the network sharing protocol", "the partition table for large disks"],
      "A new data drive must support per-file access permissions on Windows.",
      "format the drive as NTFS to gain permissions and journaling",
      ["format as exFAT for NTFS permissions", "leave the drive raw and unformatted", "format as FAT16 for extra features"]),
    c("formatting", "preparing a partition's file system, which erases its contents",
      "Choosing format on a volume wipes its index and starts the file system fresh.",
      ["cleaning the disk's outer surface only", "renaming the volume label", "defragmenting the drive's files"],
      "A reused drive must have a fresh NTFS layout before Windows touches it.",
      "format the partition during setup to build a clean file system",
      ["run chkdsk to prepare the partition", "delete only the top-level folders", "write zeros over the used space only"]),
    c("device drivers", "the software that lets Windows operate each hardware part",
      "After setup, video, sound, and network each need their matching software.",
      ["the screws that hold the card in place", "the BIOS settings for each device", "the cables connecting each device"],
      "A fresh install shows fuzzy graphics and no Wi-Fi at all.",
      "install the matching drivers for graphics and wireless hardware",
      ["replace the graphics card and Wi-Fi card", "update the monitor's on-screen menu", "reseat the RAM to wake the devices"]),
    c("Windows Update", "the built-in service that delivers patches and some drivers",
      "After setup, this service fetches security fixes and often missing drivers automatically.",
      ["an app store for paid games", "a tool that formats the system drive", "a service that restores deleted files"],
      "A fresh install must receive security patches before a user logs in for work.",
      "run Windows Update until all pending patches install",
      ["reinstall Windows to fetch the patches", "download fixes from forum links", "disable the service to stay stable"]),
    c("Windows Recovery Environment", "the offline toolset with repair and reset options",
      "When Windows will not start, this environment offers startup repair and reset from outside.",
      ["a tool inside Windows that tweaks visuals", "the support website's chat assistant", "an antivirus quarantine folder"],
      "A PC loops at the boot logo and never reaches the login screen.",
      "boot the Windows Recovery Environment and run startup repair",
      ["reinstall the printer driver offline", "boot into safe mode's screensaver", "replace the keyboard to pass the logo"])
  ],
  "SAFETY PROCEDURES": [
    c("unplug and discharge", "powering off, unplugging, and draining residual charge before opening hardware",
      "The cord leaves the wall, the button bleeds the standby, only then does the panel come off.",
      ["unplugging only after removing parts", "leaving the cord attached for grounding", "draining charge by touching two sockets"],
      "A technician must open a desktop that was running moments ago.",
      "shut down, unplug, and press the power button to drain before opening",
      ["open it while fans still spin down", "pull the SATA cable to cut power", "flip the monitor's switch off"]),
    c("ESD precautions", "strap, mat, and careful handling that keep static off components",
      "Strap on wrist, lay the mat, clip the ground — then parts may come out of bags.",
      ["spraying parts with antistatic polish", "keeping parts in plastic grocery bags", "working fast so static has no time to build"],
      "A board-level repair is scheduled on a dry afternoon at a carpeted site.",
      "set up strap and grounded mat before the first bag opens",
      ["work quickly to limit exposure time", "ground each part by touching a radiator", "wear rubber-soled shoes on carpet"]),
    c("never open the PSU", "the supply's capacitors hold dangerous charge long after unplugging",
      "No user-serviceable parts inside — the case stays shut even for dust cleaning.",
      ["a unit that self-discharges in one minute", "a supply that is safe once switched off", "a case that opens safely with insulated tools"],
      "A dusty PSU must be cleaned during annual maintenance.",
      "clean the PSU's exterior and vents only, leaving the case sealed",
      ["open the PSU and vacuum its interior", "discharge the caps with a screwdriver", "blow compressed air through the open case"]),
    c("Class C extinguisher use", "electrical fires need a non-conductive extinguishing agent",
      "The CO2 unit stands beside the bench for live-electrical fires only.",
      ["water buckets kept beside every bench", "foam units rated for wood fires", "sand buckets for electrical panels"],
      "Smoke pours from an energized server's back panel.",
      "cut power, then discharge the CO2 extinguisher at the base of the flames",
      ["douse the server with a water bottle", "fan the flames toward the smoke detector", "throw the desk's fabric cover over it"]),
    c("clear walkways", "keeping cables and boxes off paths to prevent trips and falls",
      "Cords cross under benches, never across aisles; deliveries move same-day.",
      ["cables taped across doorways for visibility", "boxes stacked beside chairs for easy reach", "cords looped loose at ankle height"],
      "A service area's aisle fills with PC boxes awaiting testing.",
      "move the boxes to shelving and route cords under the benches",
      ["tape the boxes shut and leave them", "line the aisle with boxes on their sides", "cover the cords with a loose rug"]),
    c("frayed cord replacement", "damaged plugs and frayed cords are replaced, never taped and reused",
      "The shop's extension cord shows exposed copper near the plug, so it goes to the bin, not the tape drawer.",
      ["cords wrapped in electrical tape to seal the wear", "cords that only matter if the case is open", "plugs that heal once the cord is unplugged"],
      "A borrowed power bar arrives with a cracked plug and cut jacket.",
      "tag it faulty, cut the plug off, and replace the cord before any use",
      ["wrap the cut tightly and lend it out", "plug it in to test how bad the spark is", "hide the damage under the desk edge"]),
    c("dry hands rule", "never handling energized equipment with wet hands or beside liquids",
      "Drinks stay off the service bench, and hands dry fully before any plug is touched.",
      ["gloves that make wet handling safe", "a rule that applies only to phone chargers", "liquids that are fine as long as the PC is off"],
      "A tech finishes a cold drink and must return to a live diagnostic bench.",
      "wipe hands dry and move the drink off the bench before resuming",
      ["keep the drink but hold the cup higher", "dry only the writing hand", "work faster so the wet hands matter less"]),
    c("stable work surface", "servicing gear on a flat, solid surface so nothing slides or falls",
      "The open case rests dead level on the bench, not balanced on a chair seat.",
      ["any flat-looking spot including a bed", "a wobbly table held level by folded cardboard", "a lap used as a workbench for speed"],
      "A heavy tower must be opened in a cramped room with one small desk.",
      "clear the desk, center the case fully on it, and lock the chair casters",
      ["balance the case across two chairs", "hold the panel with one knee while working", "work on the floor beside the doorway"])
  ]
};

const advanced = {
  "BIOS, CMOS, UEFI": [
    c("NVRAM", "nonvolatile storage where UEFI keeps its variables and boot entries",
      "Boot entries and settings persist in firmware storage even with the battery pulled.",
      ["a cache that stores open browser tabs", "the RAM that holds running programs", "a disk partition that mirrors Windows"],
      "A UEFI board loses its boot entry after every cold boot.",
      "inspect NVRAM variables and re-add the boot entry with the firmware's tool",
      ["replace the coin cell to hold the entry", "reinstall Windows to rewrite the entry", "clear the disk's partition table"]),
    c("CSM (Compatibility Support Module)", "the UEFI module that permits legacy BIOS-style booting",
      "Old DOS-class boots still start because the module emulates the old interface.",
      ["a module that speeds up UEFI boot times", "a driver that adds USB 3 ports to DOS", "a tool that converts GPT disks to MBR"],
      "A legacy OS installer needs BIOS-style boot on a modern UEFI board.",
      "enable CSM so the board accepts legacy BIOS-style boot",
      ["flash an older BIOS version onto the board", "disable Secure Boot and expect legacy boot", "format the installer as GPT+NTFS"]),
    c("dbx revocation list", "the Secure Boot forbidden-signature database updated by vendors",
      "When a bootloader turns malicious, vendors push dbx updates that block its key.",
      ["the list of allowed keyboard layouts", "a database of Wi-Fi networks to block", "the list of blocked Windows updates"],
      "A known-vulnerable bootloader must never start even with Secure Boot on.",
      "apply the vendor's dbx update that revokes the bad bootloader's signature",
      ["disable Secure Boot to block the loader", "add the loader's hash to the allow list", "reinstall Windows to remove the loader"]),
    c("TPM 2.0", "the hardware or firmware module that seals keys — required by Windows 11",
      "BitLocker keys and credentials live in this tamper-resistant module.",
      ["a tool that manages printer drivers", "a partition that stores recovery images", "a chip that boosts memory speed"],
      "A Windows 11 readiness check fails on an otherwise capable machine.",
      "enable the TPM 2.0 firmware module in UEFI settings",
      ["upgrade the CPU to pass the readiness check", "disable Secure Boot to satisfy the check", "add RAM to meet the module requirement"]),
    c("BitLocker with TPM sealing", "disk keys sealed to firmware and TPM state so altered boots cannot unlock",
      "Move the disk to another board and the sealed key simply will not release.",
      ["encryption unlocked by the Windows password alone", "a lock released by any USB key on boot", "protection that stops after three boots"],
      "A BitLocker drive moved to an identical spare board refuses to unlock.",
      "recover with the printed recovery key, then re-seal to the new board",
      ["clear the TPM and hope the drive opens", "format the drive and restore from email", "swap the drive back and forth until it opens"]),
    c("boot mode mismatch", "a UEFI-installed Windows will not start after switching to legacy mode",
      "The disk stays healthy, but the firmware looks for the wrong boot style and finds nothing.",
      ["a fault that physically damages the disk", "an error fixed by reinstalling the monitor driver", "a mode that only affects USB keyboards"],
      "After a firmware flip, a healthy install vanishes from the boot list.",
      "switch the firmware back to UEFI mode to match the disk's boot style",
      ["repartition the disk as MBR while in UEFI mode", "clear CMOS and retry the boot at once", "reinstall the graphics driver from recovery"]),
    c("BIOS flashback", "reflashing firmware from USB without a working CPU installed",
      "The dedicated port and button reflash the chip even when the socket sits empty.",
      ["an update delivered through Windows Update", "a flash that requires a running OS first", "a backup battery that restores firmware"],
      "A board with an unsupported CPU cannot POST to accept the new firmware.",
      "use the BIOS flashback port and button to flash the firmware CPU-less",
      ["borrow a supported CPU to POST and flash", "hot-swap the firmware chip while running", "reseat the unsupported CPU and retry POST"]),
    c("dual BIOS", "a backup firmware chip that restores a corrupted main BIOS",
      "A switch or auto-fallback hands control to the untouched spare chip.",
      ["two batteries that power the same BIOS", "two boards in one case for redundancy", "a partition that stores BIOS backups"],
      "A failed flash bricks the main firmware, but the board still boots.",
      "trigger the dual-BIOS fallback to recover from the spare chip",
      ["re-flash the corrupted chip forty times", "clear CMOS to regenerate the firmware", "swap the CPU to bypass the firmware"]),
    c("clearing CMOS", "using the jumper or removing the coin cell to reset firmware settings",
      "Jumper pins short for ten seconds, or the cell lifts a minute with power cord out.",
      ["a reset that deletes the operating system", "a procedure that runs from within Windows", "a reset that uninstalls all drivers"],
      "A forgotten firmware password blocks every setup screen.",
      "power down, clear CMOS by jumper, and reboot to defaults",
      ["reinstall Windows to clear the password", "flash the firmware to erase passwords", "hold Delete for one full minute"]),
    c("fan curves", "firmware tables mapping temperature readings to fan speeds",
      "A steeper curve spins fans sooner as the CPU heats.",
      ["charts of airflow painted on the case", "the path air takes past the heatsink", "the order in which fans start at boot"],
      "A build idles loud but overheats under load, exactly backwards.",
      "re-draw the fan curve so speeds rise with temperature under load",
      ["swap the CPU and case fan connectors", "set every fan to fixed minimum speed", "disable temperature sensors to stop noise"]),
    c("virtualization setting", "the firmware switch (VT-x/AMD-V) that lets hypervisors run virtual machines",
      "VM software refuses to start 64-bit guests until this switch turns on.",
      ["a Windows feature that doubles RAM", "a driver that speeds up video calls", "a BIOS option that overclocks safely"],
      "VM software reports VT-x disabled on a fresh machine.",
      "enable the virtualization switch in UEFI settings, then restart",
      ["reinstall the VM software as admin", "enable Secure Boot to unlock virtualization", "allocate more disk space to the VM"]),
    c("XMP memory profile", "the one-click overclock profile stored in the memory's firmware",
      "Rated 3600 MHz sticks idle at 2133 until the profile loads in setup.",
      ["a Windows setting that doubles RAM size", "a driver that overclocks the graphics card", "a BIOS option that underclocks for silence"],
      "A new memory kit benches far below its rated speed.",
      "enable the kit's XMP profile in UEFI settings",
      ["reseat the sticks into different slots", "update Windows to unlock the speed", "double the kit's voltage manually"]),
    c("firmware admin versus user password", "the admin level locks every setting; the user level mainly gates boot",
      "Setup changes demand the admin password, while daily boots ask nothing more.",
      ["two passwords of different lengths only", "a login pair used inside Windows", "one password for BIOS and one for Wi-Fi"],
      "Students must boot lab PCs but never change any firmware setting.",
      "set the admin password for setup and leave user password off",
      ["set both passwords to the same value", "set only the user password for full lockdown", "leave setup open and hide the keyboard"]),
    c("management engine firmware", "the co-processor firmware inside the chipset needing its own updates",
      "Beyond the main BIOS, the platform controller runs its own firmware that vendors patch.",
      ["a second OS inside the hard drive", "the graphics card's video BIOS", "the keyboard controller's lighting program"],
      "A platform vulnerability bulletin demands an update beyond the standard BIOS flash.",
      "apply the vendor's management engine firmware update package",
      ["reflash the main BIOS with the same version", "update the GPU's video BIOS instead", "reinstall Windows to patch the chipset"]),
    c("UEFI shell", "a built-in command environment for diagnostics and updates",
      "From the shell, firmware tools run scripts and flashers without any OS present.",
      ["a text mode inside Windows for repairs", "a Linux rescue disc for firmware", "a phone app that edits BIOS settings"],
      "A machine must run a firmware updater without any operating system installed.",
      "enter the UEFI shell and run the updater from its FS path",
      ["boot the machine from a phone via USB", "run the updater from a spinning disk", "type commands into the POST screen"])
  ],
  NETWORKING: [
    c("NAT", "the router rewriting private addresses so many devices share one public IP",
      "Twenty devices reach the internet through one public address as the router rewrites each connection.",
      ["a firewall that blocks all inbound traffic", "a service that assigns domain names", "a switch feature that doubles port speed"],
      "An office of thirty PCs holds only one public IP address from its provider.",
      "enable NAT on the gateway so all PCs share the single public address",
      ["buy thirty public addresses from the provider", "assign the public IP to each PC in turn", "bridge every PC directly to the modem"]),
    c("private IP ranges", "reserved LAN address blocks that never route on the public internet",
      "Ranges like 10.x.x.x and 192.168.x.x belong inside LANs everywhere.",
      ["address blocks reserved for government sites", "ranges reserved for public web servers", "special addresses that speed up routing"],
      "A new LAN design must pick addresses that cannot collide with internet hosts.",
      "number the LAN from the private ranges such as 192.168.10.0/24",
      ["number the LAN from a random public block", "use 1.1.1.1 addresses for the servers", "lease addresses from the ISP for each PC"]),
    c("TCP versus UDP", "TCP guarantees ordered delivery; UDP trades guarantees for speed",
      "File transfers ride TCP while live voice rides UDP and tolerates the odd lost packet.",
      ["two names for wired and wireless links", "two encryption strengths for the same protocol", "two speeds of the same cable standard"],
      "A voice-over-IP call stutters when forced through a file-transfer protocol.",
      "carry the voice over UDP for low delay instead of TCP",
      ["switch the call to TCP for reliability", "compress the voice and keep TCP", "double the bandwidth and keep TCP"]),
    c("port numbers", "16-bit labels that route traffic to the right service on a host",
      "Web traffic lands on 80 or 443 while mail lands on 25 — same host, different doors.",
      ["physical sockets on the switch chassis", "the number of devices a router supports", "the speed rating of a network card"],
      "A server runs one web site and one mail service on the same address.",
      "differentiate the services by their port numbers, 443 and 25",
      ["install two network cards for the two services", "run the services on two separate floors", "give each service its own public IP"]),
    c("static versus dynamic addressing", "fixed manual addresses versus DHCP-assigned leases",
      "Printers usually hold fixed addresses while laptops lease theirs automatically.",
      ["a choice between wired and wireless", "two speeds of DHCP assignment", "a choice of public versus private DNS"],
      "Printers must stay reachable at the same address after every reboot.",
      "assign the printers static addresses outside the DHCP lease pool",
      ["enable DHCP reservation on the printer itself", "renew the printers' leases nightly", "move the printers onto the guest Wi-Fi"]),
    c("IPv6", "the 128-bit address scheme designed to replace exhausted IPv4",
      "Modern networks run both stacks as v4 addresses run dry worldwide.",
      ["a faster version of the Ethernet cable", "the sixth Windows networking stack", "a compression for IPv4 headers"],
      "A new branch network must be designed without depending on scarce v4 space.",
      "number the branch with an IPv6 prefix alongside its IPv4 block",
      ["reuse the head office's v4 range with NAT", "number the branch with 192.168.0.x again", "apply for one shared dial-up address"]),
    c("subnetting", "carving a network into smaller ranges by borrowing host bits",
      "One /24 splits into four /26 ranges, each holding its own broadcast domain.",
      ["splitting one cable into four outlets", "dividing bandwidth equally among users", "splitting a server into virtual machines"],
      "One flat 300-host network must separate staff, printers, and guests.",
      "subnet the range so each group sits in its own smaller network",
      ["buy a switch per group and keep one flat LAN", "assign random addresses across the flat LAN", "install a second router at double cost"]),
    c("VPN tunneling", "carrying private traffic encrypted across a public network",
      "A road warrior's laptop reaches office shares through an encrypted tunnel.",
      ["a second internet line reserved for staff", "a switch that prioritizes office traffic", "a cable run between two buildings"],
      "A remote worker must reach internal file shares securely over hotel Wi-Fi.",
      "connect the worker through the office VPN tunnel",
      ["email the shared files to the worker daily", "open the file server straight to the internet", "ship a NAS drive to the worker's hotel"]),
    c("firewall rules", "allow-or-block filters applied to traffic by address, port, and direction",
      "Inbound 3389 stays blocked while outbound 443 flows to the internet.",
      ["walls that shield cables from interference", "filters that block dust from server rooms", "rules that limit each user's data quota"],
      "Remote desktop must be blocked from the internet but allowed inside.",
      "write rules that block inbound 3389 from outside while permitting it inside",
      ["disable remote desktop on every machine", "block all inbound and outbound 443", "unplug the server from the network at night"]),
    c("bandwidth versus latency", "capacity of the pipe versus the delay before the first byte",
      "A satellite link may carry gigabits yet answer a ping half a second later.",
      ["two names for the same measured speed", "upload speed versus download speed", "wired speed versus wireless speed"],
      "Video calls stutter on a line that downloads files at impressive speed.",
      "measure and address the line's latency, not just its bandwidth",
      ["upgrade to a faster bandwidth tier only", "replace the users' headsets", "move the calls to lunchtime"])
  ],
  "WINDOWS INSTALLATION": [
    c("GPT versus MBR for installation", "UEFI systems install to GPT while legacy boot needs MBR",
      "Choose the partition style before install, or the firmware will not see the bootloader.",
      ["two file systems chosen after installation", "two brands of disk that install differently", "two Windows editions with different limits"],
      "A UEFI machine's installer was prepared for MBR and the disk never boots.",
      "rebuild the installer for GPT so it matches the UEFI firmware",
      ["switch the firmware to legacy and force MBR", "delete the bootloader partition and retry", "install to a USB disk instead"]),
    c("Rufus media settings", "matching the tool's partition scheme to the target firmware",
      "GPT for UEFI, MBR for legacy — chosen before the image writes.",
      ["settings that change the installer's language only", "options that alter the license type", "toggles that pick the desktop wallpaper"],
      "A created installer boots on old machines but not on the new UEFI one.",
      "recreate the media with the GPT-for-UEFI partition scheme",
      ["recreate the media with a larger cluster size", "copy the files again in safe mode", "recreate the media as exFAT"]),
    c("local versus Microsoft account", "an offline sign-in kept on the PC versus a synced online account",
      "One keeps settings local; the other syncs files and preferences to the cloud.",
      ["two license types with different prices", "an admin account versus a guest account", "a work account versus a school email"],
      "A privacy-minded user must avoid cloud sync during a fresh setup.",
      "choose the local account option during the setup experience",
      ["sign in and disable sync later from settings", "create a Microsoft account with a fake birthdate", "skip the account and use safe mode"]),
    c("OOBE (out-of-box experience)", "the setup sequence of region, keyboard, account, and privacy choices",
      "The clickable walk-through right before the desktop appears.",
      ["the unboxing checklist printed on the carton", "the firmware screens shown at first boot", "the update dialog after the first login"],
      "A deployed PC must reach users with region and privacy pre-configured.",
      "automate the OOBE answers so users skip the manual walk-through",
      ["hide the OOBE by pulling the network cable", "let each user guess through the screens", "reinstall Windows for every user's region"]),
    c("sysprep generalize", "preparing a Windows image so it can deploy to many different machines",
      "The tool strips machine-specific identifiers before the image is captured.",
      ["a cleaner that deletes all user profiles", "a tool that shrinks the Windows folder", "a driver that works on all hardware"],
      "One golden image must deploy to fifty PCs with different hardware.",
      "run sysprep to generalize the image before capturing it",
      ["clone the disk fifty times with its identifiers", "rename each clone after deployment", "reset each clone's clock before use"]),
    c("unattended answer file", "an autounattend.xml that automates setup choices end to end",
      "Partitioning, edition, keys, and account all answer themselves from one file on the media.",
      ["a script that runs after login to set wallpaper", "a form the user fills during setup", "a log file that records setup choices"],
      "Technicians must deploy identical setups without answering any prompts.",
      "place a completed autounattend.xml on the install media",
      ["train technicians to click faster through setup", "record a macro that plays during setup", "install once and copy the drive to the rest"]),
    c("in-place repair upgrade", "reinstalling Windows over itself to fix the system while keeping apps and files",
      "Setup runs from within Windows and refreshes system files without touching programs.",
      ["a reset that wipes the drive completely", "a repair that only scans system files", "a rollback to the previous Windows version"],
      "A system boots but crashes constantly, and the user cannot lose installed software.",
      "run the in-place repair upgrade, choosing to keep files and apps",
      ["reset the PC and remove everything", "delete the program files folder to refresh", "restore an old restore point blindly"]),
    c("system image backup", "a full drive snapshot taken before touching partitions",
      "One image file holds the entire disk state so a failed install can roll back.",
      ["a backup of the Documents folder only", "a list of installed programs exported to text", "a copy of the registry hive alone"],
      "A risky repartition looms on a machine with irreplaceable local data.",
      "capture a full system image to an external drive before starting",
      ["copy the desktop folder to a USB stick", "note the installed programs on paper", "enable file history and proceed"]),
    c("Windows edition selection", "Home versus Pro choices that change features like BitLocker and domain join",
      "Pro adds the management features; Home targets personal machines.",
      ["two languages bundled with the installer", "two themes with different wallpapers", "two versions that differ in speed only"],
      "A fleet PC must join a company domain on first setup.",
      "install the Pro edition so the domain-join feature exists",
      ["install Home and add the domain feature later", "install either edition and edit the registry", "install Education and rename it to Pro"]),
    c("activation troubleshooting", "matching the license type — retail, OEM, or digital — to the install",
      "An OEM key tied to original hardware will not activate on a fresh mainboard.",
      ["a process that reuses one key on any PC", "a tool that cracks unactivated installs", "a reset that removes the license server"],
      "A repaired PC with a replaced motherboard refuses activation.",
      "reactivate by phone or link the digital license to the Microsoft account",
      ["enter the OEM key again until it accepts", "reinstall the previous Windows version", "replace the motherboard back and retry"])
  ],
  "SAFETY PROCEDURES": [
    c("uninterruptible power supply (UPS)", "a battery unit that gives time to shut down safely during outages",
      "Mains dies, and the server keeps running long enough to save and power down cleanly.",
      ["a surge strip with extra outlets", "a backup generator that runs for hours", "a battery that charges phones during outages"],
      "A file server must never lose power abruptly during brownouts.",
      "place the server on a UPS sized for a safe shutdown window",
      ["plug the server into a surge strip only", "add a second power cable to another room", "schedule nightly restarts to prevent loss"]),
    c("surge protection maintenance", "clamp blocks that divert spikes, degrading after large surges",
      "After a nearby lightning strike, the protected strip quietly stops protecting.",
      ["surge strips that last a lifetime", "protection that improves with every spike", "surge protectors that also clean power signals"],
      "A workshop's power strips took a lightning hit last storm season.",
      "replace the surge protectors and log the replacement dates",
      ["reset the strips' breakers and keep them", "test the strips with a multimeter and reuse", "daisy-chain two strips for double protection"]),
    c("solvent storage and handling", "keeping chemicals sealed, labeled, and ventilated away from heat",
      "Every bottle carries its label, sits in the cabinet, and leaves only for use.",
      ["solvents stored in open cups for quick access", "chemicals kept beside heaters to prevent gelling", "unlabeled bottles refilled from bulk drums"],
      "Three cleaning solvents crowd a workbench beside a soldering station.",
      "return the solvents to the labeled flammable cabinet away from heat",
      ["move the soldering iron closer to save steps", "decant solvents into water bottles for sharing", "store the solvents under the hot air vent"]),
    c("incident escalation", "reporting faults beyond safe authority to the right authority promptly",
      "The technician stops at the smoking transformer and calls the facility line, not self-repair.",
      ["escalation that waits for the quarterly meeting", "fixing dangerous faults quietly to save time", "escalating only after trying repairs thrice"],
      "A server rack's breaker sparks when a tech approaches the panel.",
      "stop, cordon the area, and escalate to facilities and safety officers at once",
      ["reset the breaker and continue the inspection", "note the spark in the logbook for Monday", "ask a colleague to hold the panel cover shut"]),
    c("emergency power-off awareness", "knowing the EPO switch location for energized-equipment emergencies",
      "The big red switch by the door cuts the room's power when someone is being shocked.",
      ["the light switch that also powers the racks", "the UPS's front-panel mute button", "the breaker inside each server's supply"],
      "A new hire starts in a server room full of energized equipment.",
      "walk them to the EPO switch and review when it must be used",
      ["show the coffee corner and the restrooms", "explain the fire extinguisher colors only", "hand them the room's Wi-Fi password"]),
    c("hot surface allowance", "heatsinks and soldering tips stay hot long after power-off; let them cool",
      "The iron returns to its stand and the CPU cooler waits a full minute before any hand comes near.",
      ["parts that cool the instant power is cut", "heatsinks that are safe to grip while fans still spin", "a rule that applies only to laptops"],
      "A just-shutdown workstation needs its RAM reseat right away.",
      "let the heatsink and surrounding parts cool before touching anything",
      ["grip the heatsink with a damp cloth", "blow on the fins for three seconds and proceed", "wear fingerless gloves and pull quickly"]),
    c("compressed air caution", "short bursts, an upright canister, and eye protection when blowing dust",
      "Dust flies off the heatsink in brief bursts while the can stays vertical and the glasses stay on.",
      ["one long continuous blast for speed", "a canister tipped to spray as a freeze spray", "dust removal that needs no eye protection"],
      "A dust-caked PC arrives for seasonal cleaning at the bench.",
      "take the unit outside, wear eye protection, and use short upright bursts",
      ["shake the can and blast upside down indoors", "hold the fan blades still by hand at full power", "vacuum the board with a brush attachment"]),
    c("battery handling", "swollen or leaking batteries go to proper recycling, never to the trash or a charger",
      "A laptop battery with a swollen case is unplugged, isolated in a metal container, and booked for recycling.",
      ["batteries that shrink back if left unplugged", "swollen packs that are safe once taped over", "battery disposal that only matters for car batteries"],
      "A phone-in repair reveals a pillowed battery under the trackpad.",
      "stop charging, isolate the pack in a fire-safe container, and route it to battery recycling",
      ["puncture it to release the pressure safely", "finish the repair and recharge it to test", "seal it in a plastic bag for the waste bin"])
  ]
};

module.exports = { foundational, advanced };
